/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.73
 * Generated at: 2016-12-20 08:27:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import dao.*;
import model.*;
import java.util.ArrayList;
import dao.*;
import model.*;
import java.util.ArrayList;
import dao.*;
import model.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/user/menuUser.jsp", Long.valueOf(1482061357470L));
    _jspx_dependants.put("/user/copyright.jsp", Long.valueOf(1482061357370L));
    _jspx_dependants.put("/user/category.jsp", Long.valueOf(1482061357370L));
    _jspx_dependants.put("/user/header.jsp", Long.valueOf(1482061357470L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\r\n");
      out.write("\"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html class=\"csstransforms csstransforms3d csstransitions webkit chrome win js\">\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("        <title>Photoshare - Home</title>\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"../css/socialicons.css\" />\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"../css/themeicons.css\" />\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"../css/posticons.css\" />\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"../css/base.css\" />\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"../css/style.css.php\" />\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"../css/user.css\" />\r\n");
      out.write("        <script type=\"text/javascript\" src=\"../css/jquery.js\"></script>\r\n");
      out.write("        <script type=\"text/javascript\" src=\"../css/jquery.fitvids.min.js\"></script>\r\n");
      out.write("        <script type=\"text/javascript\" src=\"../css/jquery.easing.min.js\"></script>\r\n");
      out.write("        <script type=\"text/javascript\" src=\"../css/superfish.min.js\"></script>\r\n");
      out.write("        <script type=\"text/javascript\" src=\"../css/jquery.metadata.js\"></script>\r\n");
      out.write("        <script type=\"text/javascript\" src=\"../css/jquery.jplayer.min.js\"></script>\r\n");
      out.write("        <script type=\"text/javascript\" src=\"../css/jquery.isotope.min.js\"></script>\r\n");
      out.write("        <script type=\"text/javascript\" src=\"../css/jquery.fullscreen.js\"></script>\r\n");
      out.write("        <script type=\"text/javascript\" src=\"../css/jquery.flexslider-min.js\"></script>\r\n");
      out.write("        <script type=\"text/javascript\" src=\"../css/plugins.js\"></script>\r\n");
      out.write("        <script type=\"text/javascript\" src=\"../css/script.js.php\"></script>\r\n");
      out.write("        <script type=\"text/javascript\" src=\"../css/demo-customizer.js\"></script>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body class=\"home page page-id-85 page-child parent-pageid-566 page-template-default ml-fixed-header\">\r\n");
      out.write("        <div id=\"header\" class=\"ml-header\">\r\n");
      out.write("            <div class=\"ml-wrapper\">\r\n");
      out.write("                <div class=\"clearfix ml-header-clear\"></div>\r\n");
      out.write("                ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\r\n");
      out.write("\"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<ul class=\"ml-head-menu ml-a-anim sf-js-enabled\">\r\n");
      out.write("    <li>\r\n");
      out.write("        <a href=\"home.jsp\" title=\"Home\">Home</a>   \r\n");
      out.write("    </li>\r\n");
      out.write("    <li>\r\n");
      out.write("        <a href=\"about.jsp\" title=\"About Us\">About</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li>\r\n");
      out.write("        <a href=\"feedback.jsp\" title=\"Feedback\">Feedback</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li>\r\n");
      out.write("        <a href=\"faqs.jsp\" title=\"Frequently Asked Questions\">FAQs</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li>\r\n");
      out.write("        <a href=\"contact.jsp\" title=\"Contact Us\">Contact</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"menu-item\">\r\n");
      out.write("        <a><form action=\"home.jsp?type=search\" method=\"post\">\r\n");
      out.write("                <input type=\"text\" name=\"keyword\" class=\"inputbox\"></input>\r\n");
      out.write("                <input type=\"submit\" name=\"\" title=\"Search album name or description album\" class=\"\" value=\"Search\"></input>\r\n");
      out.write("        </form></a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <div id=\"module-status\">\r\n");
      out.write("        ");

            Account sessionAcc = null;
            if (session.getAttribute("userAcc") == null) {
        
      out.write("\r\n");
      out.write("        <li class=\"menu-item\">\r\n");
      out.write("            <a href=\"loginUser.jsp\">Login</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"menu-item\">\r\n");
      out.write("            <a href=\"register.jsp\">Register</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        ");
        } else {
            MessengerDAO mesDao = new MessengerDAO();
            sessionAcc = (Account) session.getAttribute("userAcc");
            ArrayList lstMesNoRead = mesDao.getListMessengerReceiverNotRead(sessionAcc.getAccId());
            ArrayList lstReqestFriend = new FriendDAO().getListRequestFriend(sessionAcc.getAccId());
            out.print("<span class=''>Hello, " + sessionAcc.getAccUser() + " | <a href='messManager.jsp' title='Messenger'>Messenger (" + lstMesNoRead.size() + ") </a>| <a href='friend.jsp?type=request' title='Request Friend'>Request friendly (" + lstReqestFriend.size() + ") </a>| ");
        
      out.write("\r\n");
      out.write("        <a href=\"../logoutServlet?type=user\" onclick=\"return confirm('Do you really want to logout ?')\" title=\"Logout\">&nbsp;Logout</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");

        }
    
      out.write("\r\n");
      out.write("</ul>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"clearfix\"></div>\r\n");
      out.write("        <div id=\"page-85\" class=\"post-85 page type-page status-publish hentry ml-main\">\r\n");
      out.write("            <div class=\"ml-grid ml-one_full ml-first\">\r\n");
      out.write("                <div class=\"ml-filter\">\r\n");
      out.write("                    <div class=\"ml-wrapper\">\r\n");
      out.write("                        ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\r\n");
      out.write("\"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<ul id=\"ml-filters\" class=\"ml-filters1\">\r\n");
      out.write("    <li>\r\n");
      out.write("        <a href=\"home.jsp\" title=\"View all album\">All</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    ");

        CategoryDAO cateDao = new CategoryDAO();
        ArrayList lstCate = cateDao.getListCategory();
        for (int i = 0; i < lstCate.size(); i++) {
            Category cate = (Category) lstCate.get(i);
    
      out.write("\r\n");
      out.write("    <li>\r\n");
      out.write("        <a href=\"home.jsp?category=");
      out.print(cate.getCategoryId());
      out.write("\" title=\"");
      out.print( cate.getCategoryName());
      out.write('"');
      out.write('>');
      out.print( cate.getCategoryName());
      out.write("</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    ");

        }
    
      out.write("\r\n");
      out.write("</ul>");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                ");

                    if (session.getAttribute("userAcc") != null) {
                
      out.write("\r\n");
      out.write("                <div class=\"ml-filter\">\r\n");
      out.write("                    <div class=\"ml-wrapper\" >\r\n");
      out.write("                        ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\r\n");
      out.write("\"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<ul class=\"ml-filters1\">\r\n");
      out.write("    <li>\r\n");
      out.write("        <a href=\"userInfo.jsp\" title=\"Profile\">Profile</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li>\r\n");
      out.write("        <a href=\"albumManager.jsp\" title=\"Album\">Album</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li>\r\n");
      out.write("        <a href=\"uploadPicture.jsp\" title=\"Upload\">Upload</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li>\r\n");
      out.write("        <a href=\"messManager.jsp\" title=\"Messenger\">Messenger</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li>\r\n");
      out.write("        <a href=\"friend.jsp\" title=\"Friend\">Friend</a>\r\n");
      out.write("    </li>\r\n");
      out.write("</ul>");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>      \r\n");
      out.write("                ");
            
                    }
                    ArrayList lstAlbumTemp = new AlbumDAO().getListAlbum();
                    ArrayList lstUserTemp = new AccountDAO().getListAcc();
                    int totalPic = 0;
                    int totalDownload = 0;
                    int regToday = new AccountDAO().getCountRegisterToday();
                    for (int i = 0; i < lstAlbumTemp.size(); i++) {
                        Album album = (Album) lstAlbumTemp.get(i);
                        ArrayList lstPic = new PictureDAO().getListPicByAlbum(album.getAlbumId());
                        totalPic += lstPic.size();
                        totalDownload += album.getDownload();
                    }
                
      out.write("\r\n");
      out.write("                <div class=\"clearfix\"></div>\r\n");
      out.write("                <div id=\"ml-port-items\" class=\"bg\">\r\n");
      out.write("                    <div class=\"ml-wrapper\">\r\n");
      out.write("                        <div id=\"ml-port-block\" class=\"ml-port-block ml-4cols isotope\" data-cols=\"4\" style=\"position: relative; overflow: hidden; height: 900px; width: 103.448275%; margin-left: -1.515151515%;\">\r\n");
      out.write("                            <div class=\"ml-pthumb\" style=\"position: absolute; left: 0px; top: 0px;text-align:center\" >\r\n");
      out.write("                                <div class=\"\"style=\"margin-top:5px; padding-left:10px;\"><strong>Register today : ");
      out.print(regToday);
      out.write("</strong></div>\r\n");
      out.write("                                <div class=\"\" style=\"margin-top:5px; padding-left:10px;\"><strong>Users : ");
      out.print( lstUserTemp.size());
      out.write("</strong></div>\r\n");
      out.write("                                <div class=\"\" style=\"margin-top:5px; padding-left:10px;\"><strong>Albums : ");
      out.print( lstAlbumTemp.size());
      out.write("</strong></div>\r\n");
      out.write("                                <div class=\"\" style=\"margin-top:5px; padding-left:10px;\"><strong>Pictures : ");
      out.print( totalPic);
      out.write("</strong></div>\r\n");
      out.write("                                <div class=\"\" style=\"margin-top:5px; padding-left:10px;\"><strong>Downloads : ");
      out.print( totalDownload);
      out.write("</strong></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            ");

                                ArrayList lstAlbum = null;
                                if (request.getParameter("category") != null) {
                                    int categoryId = Integer.parseInt(request.getParameter("category"));
                                    lstAlbum = new AlbumDAO().getListAlbumByCategory(categoryId);
                                } else if (request.getParameter("type") != null) {
                                    String keyword = request.getParameter("keyword");
                                    lstAlbum = new AlbumDAO().searchAlbumByDes(keyword);
                                } else {
                                    lstAlbum = new AlbumDAO().getListAlbum();
                                }
                                for (int i = 0; i < lstAlbum.size(); i++) {
                                    Album album = (Album) lstAlbum.get(i);
                                    ArrayList lstPic = new PictureDAO().getListPicByAlbum(album.getAlbumId());
                                    if (lstPic.size() > 0) {
                                        Picture pic = (Picture) lstPic.get(0);
                            
      out.write("\r\n");
      out.write("                            <div class=\"ml-pthumb ml-c-people ml-c-photo1 isotope-item\" style=\"position: absolute; left: 0px; top: 0px;\" >\r\n");
      out.write("                                <a href=\"albumDetail.jsp?albumId=");
      out.print(album.getAlbumId());
      out.write("\" class=\"ml-pfull-link\">\r\n");
      out.write("                                    <img src=\"");
      out.print(pic.getPicUrl());
      out.write("\" alt=\"Home - Photoshare\" class=\"ml-pthumb-img\">\r\n");
      out.write("                                    <div class=\"ml-glare\"></div>\r\n");
      out.write("                                    <span class=\"ml-pthumb-title\">");
      out.print(album.getAlbumName());
      out.write("</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            ");

                                }}
                            
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"clearfix\"></div>\r\n");
      out.write("            <div id=\"ml-footer\" class=\"ml-footer\">\r\n");
      out.write("                <div class=\"ml-wrapper\">\r\n");
      out.write("                    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\r\n");
      out.write("\"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"ml-copy\" style=\"text-align:center\">\r\n");
      out.write("    © Copyright 2012 Photoshare.com.vn, all rights reserved - Powered by : <strong>TEAM V - C1012G .</strong>\r\n");
      out.write("    <br>Instructor : <strong>Nguyen Hung Cuong .</strong>\r\n");
      out.write("    <br>Managing agencies : <strong>BachKhoa-Aptech .</strong> \r\n");
      out.write("    <br>Address : <strong>Building HTC, 250 Hoang Quoc Viet, Cau Giay, Ha Noi .</strong>\r\n");
      out.write("    <br>Tel : <strong>(84-4).3.755.4010 .</strong>\r\n");
      out.write("    <br>License No. 254/GP-BC - Issued on 30/11/2012 .\r\n");
      out.write("    <br>Responsible for publishing : <strong>Team V - C1012G.</strong>\r\n");
      out.write("    <br>® Specify the source \"Photoshare.com.vn\" when you release the information from this website .\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
