/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.39
 * Generated at: 2017-03-19 17:17:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.Admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Article_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Header.jsp", out, false);
      out.write("\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <h4 class=\"title\">Quản lý bài viết</h4>\n");
      out.write("            <div class=\"container-fluid\" id=\"AddArticle\" title=\"Thêm mới bài viết\" ng-show=\"isShowDetail\">\n");
      out.write("                <h5 style=\"font-weight: bold;\">Thêm mới bài viết</h5>\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-md-4\" ng-class=\"myForm.Section.$invalid?'invalid form-group ':'form - group'\">\n");
      out.write("                        <label>Thể loại:</label>\n");
      out.write("                        <select  class=\"form-control\" ng-model=\"Article.Section\" name=\"Section\" ng-options=\"pm.MaThamSo as pm.DienGiai for pm in Permiss\" val-required>\n");
      out.write("                            <option value=\"\">---Chọn thể loại bài viết---</option>\n");
      out.write("                        </select>\n");
      out.write("                        <span ng-show=\"myForm.Section.$error.valRequired\" class=\"validate-text\">Thể loại là bắt buộc chọn</span>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-md-4\" ng-class=\"myForm.Status.$invalid?'invalid form-group ':'form - group'\">\n");
      out.write("                        <label>Trạng thái kích hoạt:</label>\n");
      out.write("                        <select  class=\"form-control\" ng-model=\"Article.Status\" name=\"Status\" ng-options=\"pm.MaThamSo as pm.DienGiai for pm in Permiss\" val-required>\n");
      out.write("                            <option value=\"\">---Chọn trạng thái kích hoạt---</option>\n");
      out.write("                        </select>\n");
      out.write("                        <span ng-show=\"myForm.Status.$error.valRequired\" class=\"validate-text\">Thể loại là bắt buộc chọn</span>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\" col-md-4\" ng-class=\"myForm.Title.$invalid?'invalid form-group ':'form - group'\">\n");
      out.write("                        <label>Tiêu đề bài viết:</label>\n");
      out.write("                        <input placeholder=\"Nhập tiêu đề\" type=\"text\" class=\"form-control\" ng-model=\"Article.Title\" name=\"Title\" id=\"Title\" val-required>\n");
      out.write("                        <span ng-show=\"myForm.Title.$error.valRequired\" class=\"validate-text\">Tên đăng nhập là bắt buộc nhập</span>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-md-4\">\n");
      out.write("                        <div class=\"col-md-7\">\n");
      out.write("                            <label>Ảnh tiêu đề:</label>\n");
      out.write("                            <input type=\"file\" ng-model-instant onchange=\"angular.element(this).scope().imageChoose(event)\" name=\"Image\" class=\"file\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-md-5\">\n");
      out.write("                            <div ng-repeat=\"step in stepsModel\">\n");
      out.write("                                <img class=\"thumb\" ng-src=\"{{step}}\" name=\"Image\"/>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\" col-md-4\" ng-class=\"myForm.Summary.$invalid?'invalid form-group ':'form - group'\">\n");
      out.write("                        <label>Nội dung tóm tắt:</label>\n");
      out.write("                        <input type=\"text\" class=\"form-control\" name=\"Summary\"ng-model=\"Article.Summary\" val-required>\n");
      out.write("                        <span ng-show=\"myForm.Summary.$error.valRequired\" class=\"validate-text\">Nội dung tóm tắt là bắt buộc nhập</span>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\" col-md-4\" ng-class=\"myForm.OrderNo.$invalid?'invalid form-group ':'form - group'\">\n");
      out.write("                        <label>Sắp xếp:</label>\n");
      out.write("                        <input type=\"number\" class=\"form-control\" name=\"OrderNo\"ng-model=\"Article.OrderNo\" val-required>\n");
      out.write("                        <span ng-show=\"myForm.OrderNo.$error.valRequired\" class=\"validate-text\">Sắp xếp là bắt buộc nhập</span>\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                </div>\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <label>Nội dung:</label>\n");
      out.write("                    <div class=\"col-md-12 nopadding\" ng-class=\"myForm.Content.$invalid?'invalid form-group ':'form - group'\">\n");
      out.write("                        <textarea id=\"txtEditor\" ng-model=\"Article.Content\" name=\"Content\" val-required></textarea> \n");
      out.write("                        <span ng-show=\"myForm.Content.$error.valRequired\" class=\"validate-text\">Nội dung là bắt buộc nhập</span>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-md-4\">\n");
      out.write("                        <a  href=\"#\" class=\"btn btn-primary footer\" role=\"button\" ng-click=\"ThemArticle()\"><i class=\"fa fa-floppy-o\"></i> Lưu</a>\n");
      out.write("                        <a  href=\"#\" class=\"btn btn-danger footer\" role=\"button\" ng-click=\"Huy()\"><i class=\"fa fa-floppy-o\"></i> Hủy</a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("    <div class=\"row\">\n");
      out.write("        <h5 style=\"font-weight: bold;\">Danh mục bài viết</h5>\n");
      out.write("        <table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" class=\"table table-striped table-bordered table-condensed\" id=\"example\">\n");
      out.write("            <thead>\n");
      out.write("                <tr>\n");
      out.write("                <th>Rendering engine</th>\n");
      out.write("                <th>Noi Dung</th>\n");
      out.write("                <th>Platform(s)</th>\n");
      out.write("                <th>Engine version</th>\n");
      out.write("                <th>CSS grade</th>\n");
      out.write("                </tr>\n");
      out.write("            </thead>\n");
      out.write("            <tbody>\n");
      out.write("                <tr class=\"odd gradeX\">\n");
      out.write("                <td>Trident</td>\n");
      out.write("                <td>Internet\n");
      out.write("                    Explorer 4.0</td>\n");
      out.write("                <td>Win 95+</td>\n");
      out.write("                <td class=\"center\"> 4</td>\n");
      out.write("                <td class=\"center\">X</td>\n");
      out.write("                </tr>\n");
      out.write("\n");
      out.write("            </tbody>\n");
      out.write("        </table>\n");
      out.write("        <a href=\"#\" class=\"btn btn-success\" ng-click=\"AddArticle()\">Thêm bản ghi mới</a>\n");
      out.write("        <a href=\"#\" class=\"btn btn-danger\" role=\"button\">Xóa bản ghi đã chọn</a>          \n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<script src=\"../../js/Article.js\" type=\"text/javascript\"></script>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Footer.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
