/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.39
 * Generated at: 2017-04-15 11:04:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.Admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Thamso_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Header.jsp", out, false);
      out.write("\n");
      out.write("    <div>\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <h4 class=\"title\"><i class=\"fa fa-link\"></i>Tham số hệ thống</h4>\n");
      out.write("            <div id=\"home\" class=\"tab-pane fade in active\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-md-6\" ng-class=\"myForm.TenThamSo.$invalid?'invalid form-group ':'form - group'\">\n");
      out.write("                        <div class=\"col-md-3 text-right\"><label class=\"control-label\"><span>* </span>Tên tham số:</label></div>\n");
      out.write("                        <div class=\"col-md-9\">\n");
      out.write("                            <input type=\"text\" class=\"form-control\" ng-model=\"ThamSo.TenThamSo\" name=\"TenThamSo\" id=\"TenThamSo\" val-required capitalize>\n");
      out.write("                            <span ng-show=\"myForm.TenThamSo.$error.valRequired\" class=\"validate-text\">Tên tham số là bắt buộc nhập</span>\t\n");
      out.write("                        </div>\t\t\t\t                \t\t\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-md-6\" ng-class=\"myForm.MaThamSo.$invalid?'invalid form-group ':'form - group'\">\n");
      out.write("                        <div class=\"col-md-3 text-right\"><label class=\"control-label\"><span>* </span>Mã tham số:</label></div>\n");
      out.write("                        <div class=\"col-md-9\">\n");
      out.write("                            <input type=\"text\" class=\"form-control\" ng-model=\"ThamSo.MaThamSo\" name=\"MaThamSo\" val-required capitalize>\n");
      out.write("                            <span ng-show=\"myForm.MaThamSo.$error.valRequired\" class=\"validate-text\">Mã tham số là bắt buộc nhập</span>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-md-6\" ng-class=\"myForm.TrangThai.$invalid?'invalid form-group ':'form - group'\">\n");
      out.write("                        <div class=\"col-md-3 text-right\"><label class=\"control-label\"><span>* </span>Trạng thái:</label></div>\n");
      out.write("                        <div class=\"col-md-9\">\n");
      out.write("                            <select class=\"form-control\" ng-model=\"ThamSo.TrangThai\" name=\"TrangThai\" val-required>\n");
      out.write("                                <option value=\"\">---Chọn trạng thái kích hoạt---</option>\n");
      out.write("                                <option value=\"1\">Kích hoạt</option>\n");
      out.write("                                <option value=\"0\">Không kích hoạt</option>\n");
      out.write("                            </select>\n");
      out.write("                            <span ng-show=\"myForm.TrangThai.$error.valRequired\" class=\"validate-text\">Trạng thái là bắt buộc chọn</span>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-md-6\" ng-class=\"myForm.DienGiai.$invalid?'invalid form-group ':'form - group'\">\n");
      out.write("                        <div class=\"col-md-3 text-right\"><label class=\"control-label\"><span>* </span>Diễn giải:</label></div>\n");
      out.write("                        <div class=\"col-md-9\">\n");
      out.write("                            <input type=\"text\" class=\"form-control\" ng-model=\"ThamSo.DienGiai\" name=\"DienGiai\" val-required>\n");
      out.write("                            <span ng-show=\"myForm.DienGiai.$error.valRequired\" class=\"validate-text\">Diễn giải là bắt buộc nhập</span>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-md-12 text-right\">\n");
      out.write("                        <a ng-show=\"!isEdit\" href=\"\" ng-click=\"ThemThamSo()\" class=\"btn btn-primary btn-function\"><i class=\"fa fa-floppy-o\"></i> Thêm mới</a>\n");
      out.write("                        <a ng-show=\"isEdit\" href=\"\" ng-click=\"CapNhatThamSo()\" class=\"btn btn-primary btn-function\"><i class=\"fa fa-floppy-o\"></i> Lưu</a>\n");
      out.write("                        <a ng-show=\"isEdit\" href=\"\" ng-click=\"Huy()\" class=\"btn btn-default btn-function\"><i class=\"fa fa-ban\"></i> Hủy</a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"row\"><hr>\n");
      out.write("                    <form class=\"form-inline\">\n");
      out.write("                        <div class=\"form-group col-md-3\">\n");
      out.write("                            <label >Tìm kiếm</label>\n");
      out.write("                            <input type=\"text\" ng-model=\"search\" class=\"form-control\" placeholder=\"Tìm kiếm\">\n");
      out.write("                        </div>\n");
      out.write("                        <div style=\"text-align: right;\">\n");
      out.write("                            <dir-pagination-controls\n");
      out.write("                                max-size=\"5\"\n");
      out.write("                                direction-links=\"true\"\n");
      out.write("                                boundary-links=\"true\" >\n");
      out.write("                            </dir-pagination-controls>\n");
      out.write("                        </div>\n");
      out.write("                    </form>\n");
      out.write("                    <table class=\"table table-bordered table-hover table-striped table-hover\">\n");
      out.write("                        <thead>\n");
      out.write("                            <tr>\n");
      out.write("                            <th></th>\n");
      out.write("                            <th ng-click=\"sort('Id')\" class=\"cursor\">ID</th>\n");
      out.write("                            <th ng-click=\"sort('MaThamSo')\" class=\"cursor\"><i class=\"fa fa-sort\"></i> Mã tham số</th>\n");
      out.write("                            <th ng-click=\"sort('TenThamSo')\" class=\"cursor \"><i class=\"fa fa-sort\"></i> Giá trị</th>\n");
      out.write("                            <th ng-click=\"sort('DienGiai')\" class=\"cursor\"><i class=\"fa fa-sort\"></i> Diễn giải</th>\n");
      out.write("                            <th ng-click=\"sort('TrangThai')\" class=\"cursor\"><i class=\"fa fa-sort\"></i> Trạng thái</th>\n");
      out.write("                            <th ng-click=\"sort('NgayTao')\" class=\"cursor\"><i class=\"fa fa-sort\"></i> Ngày tạo</th>\n");
      out.write("                            <th ng-click=\"sort('NgaySua')\" class=\"cursor\"><i class=\"fa fa-sort\"></i> Ngày sửa</th>\n");
      out.write("                            <th></th>\n");
      out.write("                            </tr>\n");
      out.write("                        </thead>\n");
      out.write("                        <tbody>\n");
      out.write("                            <tr dir-paginate=\"ts in TableThamSo|orderBy:sortKey:reverse|filter:search|itemsPerPage:5\" ng-class=\"{select : $index == selectIndex}\">\n");
      out.write("                            <td>\n");
      out.write("                                <input ng-model=\"ts.Checked\"  ng-true-value=\"1\" ng-false-value=\"0\" type=\"checkbox\">\n");
      out.write("                            </td>\n");
      out.write("                            <td>{{ts.Id}}</td>\n");
      out.write("                            <td>{{ts.MaThamSo}}</td>\n");
      out.write("                            <td>{{ts.TenThamSo}}</td>\n");
      out.write("                            <td>{{ts.DienGiai}}</td>\n");
      out.write("                            <td ng-show=\"ts.TrangThai == 1\">Kích hoạt</td>\n");
      out.write("                            <td ng-show=\"ts.TrangThai == 0\">Không kích hoạt</td>\n");
      out.write("                            <td>{{ts.NgayTao}}</td>\n");
      out.write("                            <td>{{ts.NgaySua}}</td>\n");
      out.write("                            <td style=\"padding: 5px 0px;\"><a class=\"btn btn-danger\" ng-click=\"XoaBanGhi($index)\"><i class=\"fa fa-trash\"></i> Xóa</a>\n");
      out.write("                            <a class=\"btn btn-default\" ng-click=\"SuaBanGhi($index)\"><i class=\"fa fa-pencil\"></i> Sửa</a></td>\n");
      out.write("                            </tr>\n");
      out.write("                        </tbody>\n");
      out.write("                    </table>\n");
      out.write("                    <a href=\"#\" class=\"btn btn-danger\" role=\"button\" ng-click=\"XoaNhieuBanGhi()\">Xóa bản ghi đã chọn</a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!--Dialog-->\n");
      out.write("\n");
      out.write("            <div id=\"Thamso-dialog-save\" title=\"Thông báo\">\n");
      out.write("                <p>\n");
      out.write("                <span class=\"ui-icon ui-icon-alert\"\n");
      out.write("                      style=\"float: left; margin: 0 7px 20px 0;\"></span>Lưu thành công\n");
      out.write("                </p>\n");
      out.write("            </div>\n");
      out.write("            <div id=\"Thamso-dialog-thongbao\" title=\"Thông báo\">\n");
      out.write("            </div>\n");
      out.write("            <!--end tab conten-->\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <script src=\"../../js/ThamSo.js\" type=\"text/javascript\"></script>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Footer.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
