/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.39
 * Generated at: 2017-03-01 17:08:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.Admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class User_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Header.jsp", out, false);
      out.write("\n");
      out.write("    <div>\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <h4 class=\"title\"><i class=\"fa fa-link\"></i>Quản lý người dùng</h4>\n");
      out.write("            <div id=\"home\" class=\"tab-pane fade in active\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <form class=\"form-inline\">\n");
      out.write("                        <div class=\"form-group col-md-3\">\n");
      out.write("                            <label >Tìm kiếm</label>\n");
      out.write("                            <input type=\"text\" ng-model=\"search\" class=\"form-control\" placeholder=\"Tìm kiếm\">\n");
      out.write("                        </div>\n");
      out.write("                        <div style=\"text-align: right;\">\n");
      out.write("                            <dir-pagination-controls\n");
      out.write("                                max-size=\"5\"\n");
      out.write("                                direction-links=\"true\"\n");
      out.write("                                boundary-links=\"true\" >\n");
      out.write("                            </dir-pagination-controls>\n");
      out.write("                        </div>\n");
      out.write("                    </form>\n");
      out.write("                    <table class=\"table table-bordered table-hover table-striped table-hover\">\n");
      out.write("                        <thead>\n");
      out.write("                            <tr>\n");
      out.write("                                <!--<th></th>-->\n");
      out.write("                            <th ng-click=\"sort('UserName')\" class=\"cursor\"><i class=\"fa fa-sort\"></i> Tên đăng nhập</th>\n");
      out.write("                            <th ng-click=\"sort('UserFullName')\" class=\"cursor \"><i class=\"fa fa-sort\"></i> Tên đầy đủ</th>\n");
      out.write("                            <th ng-click=\"sort('UserBirthday')\" class=\"cursor\"><i class=\"fa fa-sort\"></i> Ngày sinh</th>\n");
      out.write("                            <th ng-click=\"sort('UserMobilePhone')\" class=\"cursor\"><i class=\"fa fa-sort\"></i> Số điện thoại</th>\n");
      out.write("                            <th ng-click=\"sort('UserEmail')\" class=\"cursor\"><i class=\"fa fa-sort\"></i> Email</th>\n");
      out.write("                            <th ng-click=\"sort('UserPermission')\" class=\"cursor\"><i class=\"fa fa-sort\"></i> Quyền</th>\n");
      out.write("                            <th ng-click=\"sort('UserStatus')\" class=\"cursor\"><i class=\"fa fa-sort\"></i> Trạng thái</th>\n");
      out.write("                            <!--                            <th ng-click=\"sort('userCreatedDate')\" class=\"cursor\"><i class=\"fa fa-sort\"></i> Ngày tạo</th>\n");
      out.write("                                                        <th ng-click=\"sort('userEditedDate')\" class=\"cursor\"><i class=\"fa fa-sort\"></i> Ngày sửa</th>-->\n");
      out.write("                            <th></th>\n");
      out.write("                            </tr>\n");
      out.write("                        </thead>\n");
      out.write("                        <tbody>\n");
      out.write("                            <tr dir-paginate=\"user in TableUser|orderBy:sortKey:reverse|filter:search|itemsPerPage:5\" ng-class=\"{select : $index == selectIndex}\">\n");
      out.write("                                <!--                            <td>\n");
      out.write("                                                                <input ng-model=\"user.Checked\"  ng-true-value=\"1\" ng-false-value=\"0\" type=\"checkbox\">\n");
      out.write("                                                            </td>-->\n");
      out.write("                            <td>{{user.UserName}}</td>\n");
      out.write("                            <td style=\"max-width: 200px;\">{{user.UserFullName}}</td>\n");
      out.write("                            <td>{{user.UserBirthday}}</td>\n");
      out.write("                            <td>{{user.UserMobilePhone}}</td>\n");
      out.write("                            <td>{{user.UserEmail}}</td>\n");
      out.write("                            <td>{{user.UserPermission}}</td>\n");
      out.write("                            <td>{{user.UserStatus}}</td>\n");
      out.write("                            <!--                            <td>{{user.userCreatedDate}}</td>\n");
      out.write("                                                        <td>{{user.userEditedDate}}</td>-->\n");
      out.write("                            <td style=\"padding: 5px 0px;\"><a class=\"btn btn-danger\" ng-click=\"XoaBanGhi($index)\"><i class=\"fa fa-trash\"></i> Xóa</a>\n");
      out.write("                                <a class=\"btn btn-default\" ng-click=\"SuaBanGhi($index)\"><i class=\"fa fa-pencil\"></i> Sửa</a></td>\n");
      out.write("                            </tr>\n");
      out.write("                        </tbody>\n");
      out.write("                    </table>\n");
      out.write("                </div><hr>\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-md-3\"><a class=\"btn btn-primary btn-function\" ng-click=\"ShowPopupThem()\">Thêm tài khoản</a></div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div id=\"User-dialog-save\" title=\"Thông báo\">\n");
      out.write("            <p>\n");
      out.write("            <span class=\"ui-icon ui-icon-alert\"\n");
      out.write("                  style=\"float: left; margin: 0 7px 20px 0;\"></span>Lưu thành công\n");
      out.write("            </p>\n");
      out.write("        </div>\n");
      out.write("        <div id=\"User-dialog-thongbao\" title=\"Thông báo\">\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!--Popup thêm mới User-->\n");
      out.write("        <div id=\"Them-User\" title=\"Thêm mới User\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\" col-md-6\" ng-class=\"myForm.UserName.$invalid?'invalid form-group ':'form - group'\">\n");
      out.write("                    <label>Tên đăng nhập:</label>\n");
      out.write("                    <input placeholder=\"Nhập tên đăng nhập\" type=\"text\" class=\"form-control\" ng-model=\"User.UserName\" name=\"UserName\" id=\"UserName\" val-required>\n");
      out.write("                    <span ng-show=\"myForm.UserName.$error.valRequired\" class=\"validate-text\">Tên đăng nhập là bắt buộc nhập</span>\n");
      out.write("                </div>\n");
      out.write("                <div class=\" col-md-6\" ng-class=\"myForm.UserPass.$invalid?'invalid form-group ':'form - group'\">\n");
      out.write("                    <label>Mật khẩu:</label>\n");
      out.write("                    <input type=\"password\" placeholder=\"Nhập số mật khẩu\" class=\"form-control\" ng-model=\"User.UserPass\" name=\"UserPass\" val-required ng-disabled=\"CheckedResetPass == 0\">\n");
      out.write("                    <span ng-show=\"myForm.UserPass.$error.valRequired\" class=\"validate-text\">Mật khẩu là bắt buộc nhập</span>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\" col-md-6\" ng-class=\"myForm.UserFullName.$invalid?'invalid form-group ':'form - group'\">\n");
      out.write("                    <label>Tên đầy đủ:</label>\n");
      out.write("                    <input type=\"text\" placeholder=\"Nhập tên đầy đủ\" class=\"form-control\" ng-model=\"User.UserFullName\" name=\"UserFullName\" val-required>\n");
      out.write("                    <span ng-show=\"myForm.UserFullName.$error.valRequired\" class=\"validate-text\">Tên là bắt buộc nhập</span>\n");
      out.write("                </div>\n");
      out.write("                <div class=\" col-md-6\" ng-class=\"myForm.UserBirthday.$invalid?'invalid form-group ':'form - group'\">\n");
      out.write("                    <label>Ngày sinh:</label>\n");
      out.write("                    <input type=\"text\" placeholder=\"Nhập ngày sinh\" class=\"form-control datepicker\" ng-model=\"User.UserBirthday\" name=\"UserBirthday\" val-required >\n");
      out.write("                    <span ng-show=\"myForm.UserBirthday.$error.valRequired\" class=\"validate-text\">Ngày sinh là bắt buộc nhập</span>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\" col-md-6\" ng-class=\"myForm.UserMobilePhone.$invalid?'invalid form-group ':'form - group'\">\n");
      out.write("                    <label>Số điện thoại:</label>\n");
      out.write("                    <input placeholder=\"Nhập số điện thoại\" type=\"number\" class=\"form-control\" ng-model=\"User.UserMobilePhone\" name=\"UserMobilePhone\" val-required>\n");
      out.write("                    <span ng-show=\"myForm.UserMobilePhone.$error.valRequired\" class=\"validate-text\">Số điện thoại là bắt buộc nhập</span>\n");
      out.write("                </div>\n");
      out.write("                <div class=\" col-md-6\" ng-class=\"myForm.UserEmail.$invalid?'invalid form-group ':'form - group'\">\n");
      out.write("                    <label>Email:</label>\n");
      out.write("                    <input type=\"email\" placeholder=\"Nhập địa chỉ email\" class=\"form-control\" ng-model=\"User.UserEmail\" name=\"UserEmail\" val-required>\n");
      out.write("                    <span ng-show=\"myForm.UserEmail.$error.valRequired\" class=\"validate-text\">Email là bắt buộc nhập</span>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-md-6\" ng-class=\"myForm.UserPermission.$invalid?'invalid form-group ':'form - group'\">\n");
      out.write("                    <label>Quyền tài khoản:</label>\n");
      out.write("                    <select  class=\"form-control\" ng-model=\"User.UserPermission\" name=\"UserPermission\" ng-options=\"pm.MaThamSo as pm.DienGiai for pm in Permiss\" val-required>\n");
      out.write("                        <option value=\"\">---Chọn quyền tài khoản---</option>\n");
      out.write("                    </select>\n");
      out.write("                    <span ng-show=\"myForm.UserPermission.$error.valRequired\" class=\"validate-text\">Quyền tài khoản là bắt buộc chọn</span>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-6\" ng-class=\"myForm.UserStatus.$invalid?'invalid form-group ':'form - group'\">\n");
      out.write("                    <label>Trạng thái kích hoạt:</label>\n");
      out.write("                    <select class=\"form-control\" ng-model=\"User.UserStatus\" name=\"UserStatus\" ng-options=\"TT.MaThamSo as TT.DienGiai for TT in TrangThai\" val-required>\n");
      out.write("                        <option value=\"\">---Chọn trạng thái---</option>\n");
      out.write("                    </select>\n");
      out.write("                    <span ng-show=\"myForm.UserStatus.$error.valRequired\" class=\"validate-text\">Trạng thái là bắt buộc chọn</span>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-md-6\">\n");
      out.write("                    <a style=\"color: white !important;\" class=\"btn btn-primary btn-function\" ng-click=\"ThemUser()\"><i class=\"fa fa-floppy-o\"></i> Lưu</a>\n");
      out.write("                    <a style=\"color: white !important;\" class=\"btn btn-danger btn-function\" ng-click=\"ClosePopupThem()\"><i class=\"fa fa-ban\"></i> Hủy</a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("        <!--Popup sửa User-->\n");
      out.write("        <div id=\"Sua-User\" title=\"Thêm mới User\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\" col-md-6\" ng-class=\"myForm.UserName.$invalid?'invalid form-group ':'form - group'\">\n");
      out.write("                    <label>Tên đăng nhập:</label>\n");
      out.write("                    <input placeholder=\"Nhập tên đăng nhập\" type=\"text\" class=\"form-control\" ng-model=\"User.UserName\" name=\"UserName\" id=\"UserName\" val-required>\n");
      out.write("                    <span ng-show=\"myForm.UserName.$error.valRequired\" class=\"validate-text\">Tên đăng nhập là bắt buộc nhập</span>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-6\" ng-class=\"myForm.UserPermission.$invalid?'invalid form-group ':'form - group'\">\n");
      out.write("                    <label>Quyền tài khoản:</label>\n");
      out.write("                    <select  class=\"form-control\" ng-model=\"User.UserPermission\" name=\"UserPermission\" ng-options=\"pm.MaThamSo as pm.DienGiai for pm in Permiss\" val-required>\n");
      out.write("                        <option value=\"\">---Chọn quyền tài khoản---</option>\n");
      out.write("                    </select>\n");
      out.write("                    <span ng-show=\"myForm.UserPermission.$error.valRequired\" class=\"validate-text\">Quyền tài khoản là bắt buộc chọn</span>\n");
      out.write("                </div>\n");
      out.write("                <!--                <div class=\" col-md-6\" ng-class=\"myForm.UserPass.$invalid?'invalid form-group ':'form - group'\">\n");
      out.write("                                    <label>Mật khẩu:</label>\n");
      out.write("                                    <input type=\"password\" placeholder=\"Nhập số mật khẩu\" class=\"form-control\" ng-model=\"User.UserPass\" name=\"UserPass\" val-required ng-disabled=\"CheckedResetPass == 0\">\n");
      out.write("                                    <span ng-show=\"myForm.UserPass.$error.valRequired\" class=\"validate-text\">Mật khẩu là bắt buộc nhập</span>\n");
      out.write("                                </div>-->\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\" col-md-6\" ng-class=\"myForm.UserFullName.$invalid?'invalid form-group ':'form - group'\">\n");
      out.write("                    <label>Tên đầy đủ:</label>\n");
      out.write("                    <input type=\"text\" placeholder=\"Nhập tên đầy đủ\" class=\"form-control\" ng-model=\"User.UserFullName\" name=\"UserFullName\" val-required>\n");
      out.write("                    <span ng-show=\"myForm.UserFullName.$error.valRequired\" class=\"validate-text\">Tên là bắt buộc nhập</span>\n");
      out.write("                </div>\n");
      out.write("                <div class=\" col-md-6\" ng-class=\"myForm.UserBirthday.$invalid?'invalid form-group ':'form - group'\">\n");
      out.write("                    <label>Ngày sinh:</label>\n");
      out.write("                    <input type=\"text\" placeholder=\"Nhập ngày sinh\" class=\"form-control datepicker\" ng-model=\"User.UserBirthday\" name=\"UserBirthday\" val-required >\n");
      out.write("                    <span ng-show=\"myForm.UserBirthday.$error.valRequired\" class=\"validate-text\">Ngày sinh là bắt buộc nhập</span>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\" col-md-6\" ng-class=\"myForm.UserMobilePhone.$invalid?'invalid form-group ':'form - group'\">\n");
      out.write("                    <label>Số điện thoại:</label>\n");
      out.write("                    <input placeholder=\"Nhập số điện thoại\" type=\"number\" class=\"form-control\" ng-model=\"User.UserMobilePhone\" name=\"UserMobilePhone\" val-required>\n");
      out.write("                    <span ng-show=\"myForm.UserMobilePhone.$error.valRequired\" class=\"validate-text\">Số điện thoại là bắt buộc nhập</span>\n");
      out.write("                </div>\n");
      out.write("                <div class=\" col-md-6\" ng-class=\"myForm.UserEmail.$invalid?'invalid form-group ':'form - group'\">\n");
      out.write("                    <label>Email:</label>\n");
      out.write("                    <input type=\"email\" placeholder=\"Nhập địa chỉ email\" class=\"form-control\" ng-model=\"User.UserEmail\" name=\"UserEmail\" val-required>\n");
      out.write("                    <span ng-show=\"myForm.UserEmail.$error.valRequired\" class=\"validate-text\">Email là bắt buộc nhập</span>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-md-6\" ng-class=\"myForm.UserStatus.$invalid?'invalid form-group ':'form - group'\">\n");
      out.write("                    <label>Trạng thái kích hoạt:</label>\n");
      out.write("                    <select class=\"form-control\" ng-model=\"User.UserStatus\" name=\"UserStatus\" ng-options=\"TT.MaThamSo as TT.DienGiai for TT in TrangThai\" val-required>\n");
      out.write("                        <option value=\"\">---Chọn trạng thái---</option>\n");
      out.write("                    </select>\n");
      out.write("                    <span ng-show=\"myForm.UserStatus.$error.valRequired\" class=\"validate-text\">Trạng thái là bắt buộc chọn</span>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-md-6\">\n");
      out.write("                    <a style=\"color: white !important;\" class=\"btn btn-primary btn-function\" ng-click=\"ThemUser()\"><i class=\"fa fa-floppy-o\"></i> Lưu</a>\n");
      out.write("                    <a style=\"color: white !important;\" class=\"btn btn-danger btn-function\" ng-click=\"ClosePopupThem()\"><i class=\"fa fa-ban\"></i> Hủy</a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("        <!--Popup đổi mật khẩu-->\n");
      out.write("        <div id=\"Doi_MK\" title=\"Thêm mới User\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\" col-md-6\" ng-class=\"myForm.UserName.$invalid?'invalid form-group ':'form - group'\">\n");
      out.write("                    <label>Tên đăng nhập:</label>\n");
      out.write("                    <input placeholder=\"Nhập tên đăng nhập\" type=\"text\" class=\"form-control\" ng-model=\"User.UserName\" name=\"UserName\" id=\"UserName\" val-required>\n");
      out.write("                    <span ng-show=\"myForm.UserName.$error.valRequired\" class=\"validate-text\">Tên đăng nhập là bắt buộc nhập</span>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\" col-md-6\" ng-class=\"myForm.UserPass.$invalid?'invalid form-group ':'form - group'\">\n");
      out.write("                    <label>Mật khẩu:</label>\n");
      out.write("                    <input type=\"password\" placeholder=\"Nhập số mật khẩu\" class=\"form-control\" ng-model=\"User.UserPass\" name=\"UserPass\" val-required ng-disabled=\"CheckedResetPass == 0\">\n");
      out.write("                    <span ng-show=\"myForm.UserPass.$error.valRequired\" class=\"validate-text\">Mật khẩu là bắt buộc nhập</span>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\" col-md-6\" ng-class=\"myForm.UserFullName.$invalid?'invalid form-group ':'form - group'\">\n");
      out.write("                    <label>Nhập lại mật khẩu:</label>\n");
      out.write("                    <input type=\"text\" placeholder=\"Nhập tên đầy đủ\" class=\"form-control\" ng-model=\"User.UserFullName\" name=\"UserFullName\" val-required>\n");
      out.write("                    <span ng-show=\"myForm.UserFullName.$error.valRequired\" class=\"validate-text\">Tên là bắt buộc nhập</span>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-md-6\">\n");
      out.write("                    <a style=\"color: white !important;\" class=\"btn btn-primary btn-function\" ng-click=\"ThemUser()\"><i class=\"fa fa-floppy-o\"></i> Lưu</a>\n");
      out.write("                    <a style=\"color: white !important;\" class=\"btn btn-danger btn-function\" ng-click=\"ClosePopupThem()\"><i class=\"fa fa-ban\"></i> Hủy</a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <script src=\"../../js/User.js\" type=\"text/javascript\"></script>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Footer.jsp", out, false);
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
