package Entities;
// Generated Feb 27, 2017 11:51:07 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tblaccount generated by hbm2java
 */
public class Tblaccount  implements java.io.Serializable {


     private Integer accountId;
     private int accountCustomerId;
     private Integer accountMoney;
     private Date accountActivedDate;
     private String accountNotes;
     private Integer accountCurrentMoney;
     private Short accountType;

    public Tblaccount() {
    }

	
    public Tblaccount(int accountCustomerId) {
        this.accountCustomerId = accountCustomerId;
    }
    public Tblaccount(int accountCustomerId, Integer accountMoney, Date accountActivedDate, String accountNotes, Integer accountCurrentMoney, Short accountType) {
       this.accountCustomerId = accountCustomerId;
       this.accountMoney = accountMoney;
       this.accountActivedDate = accountActivedDate;
       this.accountNotes = accountNotes;
       this.accountCurrentMoney = accountCurrentMoney;
       this.accountType = accountType;
    }
   
    public Integer getAccountId() {
        return this.accountId;
    }
    
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }
    public int getAccountCustomerId() {
        return this.accountCustomerId;
    }
    
    public void setAccountCustomerId(int accountCustomerId) {
        this.accountCustomerId = accountCustomerId;
    }
    public Integer getAccountMoney() {
        return this.accountMoney;
    }
    
    public void setAccountMoney(Integer accountMoney) {
        this.accountMoney = accountMoney;
    }
    public Date getAccountActivedDate() {
        return this.accountActivedDate;
    }
    
    public void setAccountActivedDate(Date accountActivedDate) {
        this.accountActivedDate = accountActivedDate;
    }
    public String getAccountNotes() {
        return this.accountNotes;
    }
    
    public void setAccountNotes(String accountNotes) {
        this.accountNotes = accountNotes;
    }
    public Integer getAccountCurrentMoney() {
        return this.accountCurrentMoney;
    }
    
    public void setAccountCurrentMoney(Integer accountCurrentMoney) {
        this.accountCurrentMoney = accountCurrentMoney;
    }
    public Short getAccountType() {
        return this.accountType;
    }
    
    public void setAccountType(Short accountType) {
        this.accountType = accountType;
    }




}


