package Entities;
// Generated Mar 19, 2017 11:45:26 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tblalbum generated by hbm2java
 */
@Entity
@Table(name="tblalbum"
    ,catalog="motchangduong_data"
)
public class Tblalbum  implements java.io.Serializable {


     private Integer albumId;
     private String albumTitle;
     private String albumImage;
     private Integer albumCategoryId;
     private Integer albumSectionId;
     private Integer albumVisited;
     private Integer albumOrderNo;
     private String albumStatus;
     private Date albumCreatDate;
     private Date albumEditDate;
     private String albumNotes;

    public Tblalbum() {
    }

    public Tblalbum(String albumTitle, String albumImage, Integer albumCategoryId, Integer albumSectionId, Integer albumVisited, Integer albumOrderNo, String albumStatus, Date albumCreatDate, Date albumEditDate, String albumNotes) {
       this.albumTitle = albumTitle;
       this.albumImage = albumImage;
       this.albumCategoryId = albumCategoryId;
       this.albumSectionId = albumSectionId;
       this.albumVisited = albumVisited;
       this.albumOrderNo = albumOrderNo;
       this.albumStatus = albumStatus;
       this.albumCreatDate = albumCreatDate;
       this.albumEditDate = albumEditDate;
       this.albumNotes = albumNotes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="album_id", unique=true, nullable=false)
    public Integer getAlbumId() {
        return this.albumId;
    }
    
    public void setAlbumId(Integer albumId) {
        this.albumId = albumId;
    }

    
    @Column(name="album_title", length=45)
    public String getAlbumTitle() {
        return this.albumTitle;
    }
    
    public void setAlbumTitle(String albumTitle) {
        this.albumTitle = albumTitle;
    }

    
    @Column(name="album_image", length=200)
    public String getAlbumImage() {
        return this.albumImage;
    }
    
    public void setAlbumImage(String albumImage) {
        this.albumImage = albumImage;
    }

    
    @Column(name="album_category_id")
    public Integer getAlbumCategoryId() {
        return this.albumCategoryId;
    }
    
    public void setAlbumCategoryId(Integer albumCategoryId) {
        this.albumCategoryId = albumCategoryId;
    }

    
    @Column(name="album_section_id")
    public Integer getAlbumSectionId() {
        return this.albumSectionId;
    }
    
    public void setAlbumSectionId(Integer albumSectionId) {
        this.albumSectionId = albumSectionId;
    }

    
    @Column(name="album_visited")
    public Integer getAlbumVisited() {
        return this.albumVisited;
    }
    
    public void setAlbumVisited(Integer albumVisited) {
        this.albumVisited = albumVisited;
    }

    
    @Column(name="album_order_no")
    public Integer getAlbumOrderNo() {
        return this.albumOrderNo;
    }
    
    public void setAlbumOrderNo(Integer albumOrderNo) {
        this.albumOrderNo = albumOrderNo;
    }

    
    @Column(name="album_status", length=20)
    public String getAlbumStatus() {
        return this.albumStatus;
    }
    
    public void setAlbumStatus(String albumStatus) {
        this.albumStatus = albumStatus;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="album_creat_date", length=19)
    public Date getAlbumCreatDate() {
        return this.albumCreatDate;
    }
    
    public void setAlbumCreatDate(Date albumCreatDate) {
        this.albumCreatDate = albumCreatDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="album_edit_date", length=19)
    public Date getAlbumEditDate() {
        return this.albumEditDate;
    }
    
    public void setAlbumEditDate(Date albumEditDate) {
        this.albumEditDate = albumEditDate;
    }

    
    @Column(name="album_notes", length=500)
    public String getAlbumNotes() {
        return this.albumNotes;
    }
    
    public void setAlbumNotes(String albumNotes) {
        this.albumNotes = albumNotes;
    }




}


