package Entities;
// Generated Feb 10, 2017 12:03:07 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tblarticle generated by hbm2java
 */
public class Tblarticle  implements java.io.Serializable {


     private Integer articleId;
     private String articleTitle;
     private String articleSummary;
     private String articleContent;
     private Date articleCreatedDate;
     private String articleLastModified;
     private String articleImage;
     private Integer articleCategoryId;
     private Integer articleSectionId;
     private Integer articleVisited;
     private String articleAuthorName;
     private Boolean articleEnable;
     private String articleUrlLink;
     private String articleTag;
     private String articleTitleEn;
     private String articleSummaryEn;
     private String articleContentEn;
     private String articleTagEn;
     private Integer articleFee;
     private Boolean articleIsfee;
     private Boolean articleDelete;
     private Date articleDeletedDate;
     private Date articleRestoredDate;
     private String articleModifiedAuthorName;
     private Short articleAuthorPermission;
     private String articleSource;
     private Short articleLanguage;
     private Boolean articleFocus;
     private Boolean articleForhome;
     private Short articleType;
     private Integer articleOrderNo;
     private String articleStatus;

    public Tblarticle() {
    }

    public Tblarticle(String articleTitle, String articleSummary, String articleContent, Date articleCreatedDate, String articleLastModified, String articleImage, Integer articleCategoryId, Integer articleSectionId, Integer articleVisited, String articleAuthorName, Boolean articleEnable, String articleUrlLink, String articleTag, String articleTitleEn, String articleSummaryEn, String articleContentEn, String articleTagEn, Integer articleFee, Boolean articleIsfee, Boolean articleDelete, Date articleDeletedDate, Date articleRestoredDate, String articleModifiedAuthorName, Short articleAuthorPermission, String articleSource, Short articleLanguage, Boolean articleFocus, Boolean articleForhome, Short articleType, Integer articleOrderNo, String articleStatus) {
       this.articleTitle = articleTitle;
       this.articleSummary = articleSummary;
       this.articleContent = articleContent;
       this.articleCreatedDate = articleCreatedDate;
       this.articleLastModified = articleLastModified;
       this.articleImage = articleImage;
       this.articleCategoryId = articleCategoryId;
       this.articleSectionId = articleSectionId;
       this.articleVisited = articleVisited;
       this.articleAuthorName = articleAuthorName;
       this.articleEnable = articleEnable;
       this.articleUrlLink = articleUrlLink;
       this.articleTag = articleTag;
       this.articleTitleEn = articleTitleEn;
       this.articleSummaryEn = articleSummaryEn;
       this.articleContentEn = articleContentEn;
       this.articleTagEn = articleTagEn;
       this.articleFee = articleFee;
       this.articleIsfee = articleIsfee;
       this.articleDelete = articleDelete;
       this.articleDeletedDate = articleDeletedDate;
       this.articleRestoredDate = articleRestoredDate;
       this.articleModifiedAuthorName = articleModifiedAuthorName;
       this.articleAuthorPermission = articleAuthorPermission;
       this.articleSource = articleSource;
       this.articleLanguage = articleLanguage;
       this.articleFocus = articleFocus;
       this.articleForhome = articleForhome;
       this.articleType = articleType;
       this.articleOrderNo = articleOrderNo;
       this.articleStatus = articleStatus;
    }
   
    public Integer getArticleId() {
        return this.articleId;
    }
    
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }
    public String getArticleTitle() {
        return this.articleTitle;
    }
    
    public void setArticleTitle(String articleTitle) {
        this.articleTitle = articleTitle;
    }
    public String getArticleSummary() {
        return this.articleSummary;
    }
    
    public void setArticleSummary(String articleSummary) {
        this.articleSummary = articleSummary;
    }
    public String getArticleContent() {
        return this.articleContent;
    }
    
    public void setArticleContent(String articleContent) {
        this.articleContent = articleContent;
    }
    public Date getArticleCreatedDate() {
        return this.articleCreatedDate;
    }
    
    public void setArticleCreatedDate(Date articleCreatedDate) {
        this.articleCreatedDate = articleCreatedDate;
    }
    public String getArticleLastModified() {
        return this.articleLastModified;
    }
    
    public void setArticleLastModified(String articleLastModified) {
        this.articleLastModified = articleLastModified;
    }
    public String getArticleImage() {
        return this.articleImage;
    }
    
    public void setArticleImage(String articleImage) {
        this.articleImage = articleImage;
    }
    public Integer getArticleCategoryId() {
        return this.articleCategoryId;
    }
    
    public void setArticleCategoryId(Integer articleCategoryId) {
        this.articleCategoryId = articleCategoryId;
    }
    public Integer getArticleSectionId() {
        return this.articleSectionId;
    }
    
    public void setArticleSectionId(Integer articleSectionId) {
        this.articleSectionId = articleSectionId;
    }
    public Integer getArticleVisited() {
        return this.articleVisited;
    }
    
    public void setArticleVisited(Integer articleVisited) {
        this.articleVisited = articleVisited;
    }
    public String getArticleAuthorName() {
        return this.articleAuthorName;
    }
    
    public void setArticleAuthorName(String articleAuthorName) {
        this.articleAuthorName = articleAuthorName;
    }
    public Boolean getArticleEnable() {
        return this.articleEnable;
    }
    
    public void setArticleEnable(Boolean articleEnable) {
        this.articleEnable = articleEnable;
    }
    public String getArticleUrlLink() {
        return this.articleUrlLink;
    }
    
    public void setArticleUrlLink(String articleUrlLink) {
        this.articleUrlLink = articleUrlLink;
    }
    public String getArticleTag() {
        return this.articleTag;
    }
    
    public void setArticleTag(String articleTag) {
        this.articleTag = articleTag;
    }
    public String getArticleTitleEn() {
        return this.articleTitleEn;
    }
    
    public void setArticleTitleEn(String articleTitleEn) {
        this.articleTitleEn = articleTitleEn;
    }
    public String getArticleSummaryEn() {
        return this.articleSummaryEn;
    }
    
    public void setArticleSummaryEn(String articleSummaryEn) {
        this.articleSummaryEn = articleSummaryEn;
    }
    public String getArticleContentEn() {
        return this.articleContentEn;
    }
    
    public void setArticleContentEn(String articleContentEn) {
        this.articleContentEn = articleContentEn;
    }
    public String getArticleTagEn() {
        return this.articleTagEn;
    }
    
    public void setArticleTagEn(String articleTagEn) {
        this.articleTagEn = articleTagEn;
    }
    public Integer getArticleFee() {
        return this.articleFee;
    }
    
    public void setArticleFee(Integer articleFee) {
        this.articleFee = articleFee;
    }
    public Boolean getArticleIsfee() {
        return this.articleIsfee;
    }
    
    public void setArticleIsfee(Boolean articleIsfee) {
        this.articleIsfee = articleIsfee;
    }
    public Boolean getArticleDelete() {
        return this.articleDelete;
    }
    
    public void setArticleDelete(Boolean articleDelete) {
        this.articleDelete = articleDelete;
    }
    public Date getArticleDeletedDate() {
        return this.articleDeletedDate;
    }
    
    public void setArticleDeletedDate(Date articleDeletedDate) {
        this.articleDeletedDate = articleDeletedDate;
    }
    public Date getArticleRestoredDate() {
        return this.articleRestoredDate;
    }
    
    public void setArticleRestoredDate(Date articleRestoredDate) {
        this.articleRestoredDate = articleRestoredDate;
    }
    public String getArticleModifiedAuthorName() {
        return this.articleModifiedAuthorName;
    }
    
    public void setArticleModifiedAuthorName(String articleModifiedAuthorName) {
        this.articleModifiedAuthorName = articleModifiedAuthorName;
    }
    public Short getArticleAuthorPermission() {
        return this.articleAuthorPermission;
    }
    
    public void setArticleAuthorPermission(Short articleAuthorPermission) {
        this.articleAuthorPermission = articleAuthorPermission;
    }
    public String getArticleSource() {
        return this.articleSource;
    }
    
    public void setArticleSource(String articleSource) {
        this.articleSource = articleSource;
    }
    public Short getArticleLanguage() {
        return this.articleLanguage;
    }
    
    public void setArticleLanguage(Short articleLanguage) {
        this.articleLanguage = articleLanguage;
    }
    public Boolean getArticleFocus() {
        return this.articleFocus;
    }
    
    public void setArticleFocus(Boolean articleFocus) {
        this.articleFocus = articleFocus;
    }
    public Boolean getArticleForhome() {
        return this.articleForhome;
    }
    
    public void setArticleForhome(Boolean articleForhome) {
        this.articleForhome = articleForhome;
    }
    public Short getArticleType() {
        return this.articleType;
    }
    
    public void setArticleType(Short articleType) {
        this.articleType = articleType;
    }
    public Integer getArticleOrderNo() {
        return this.articleOrderNo;
    }
    
    public void setArticleOrderNo(Integer articleOrderNo) {
        this.articleOrderNo = articleOrderNo;
    }
    public String getArticleStatus() {
        return this.articleStatus;
    }
    
    public void setArticleStatus(String articleStatus) {
        this.articleStatus = articleStatus;
    }




}


