package Entities;
// Generated Mar 19, 2017 11:45:26 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tbladvertise generated by hbm2java
 */
@Entity
@Table(name="tbladvertise"
    ,catalog="motchangduong_data"
)
public class Tbladvertise  implements java.io.Serializable {


     private Integer advertiseId;
     private String advertiseTitle;
     private String advertiseUrl;
     private String advertiseNotes;
     private Short advertiseType;
     private Short advertiseDisplay;
     private String advertiseImage;

    public Tbladvertise() {
    }

	
    public Tbladvertise(String advertiseTitle, String advertiseImage) {
        this.advertiseTitle = advertiseTitle;
        this.advertiseImage = advertiseImage;
    }
    public Tbladvertise(String advertiseTitle, String advertiseUrl, String advertiseNotes, Short advertiseType, Short advertiseDisplay, String advertiseImage) {
       this.advertiseTitle = advertiseTitle;
       this.advertiseUrl = advertiseUrl;
       this.advertiseNotes = advertiseNotes;
       this.advertiseType = advertiseType;
       this.advertiseDisplay = advertiseDisplay;
       this.advertiseImage = advertiseImage;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="advertise_id", unique=true, nullable=false)
    public Integer getAdvertiseId() {
        return this.advertiseId;
    }
    
    public void setAdvertiseId(Integer advertiseId) {
        this.advertiseId = advertiseId;
    }

    
    @Column(name="advertise_title", nullable=false, length=300)
    public String getAdvertiseTitle() {
        return this.advertiseTitle;
    }
    
    public void setAdvertiseTitle(String advertiseTitle) {
        this.advertiseTitle = advertiseTitle;
    }

    
    @Column(name="advertise_url", length=200)
    public String getAdvertiseUrl() {
        return this.advertiseUrl;
    }
    
    public void setAdvertiseUrl(String advertiseUrl) {
        this.advertiseUrl = advertiseUrl;
    }

    
    @Column(name="advertise_notes", length=65535)
    public String getAdvertiseNotes() {
        return this.advertiseNotes;
    }
    
    public void setAdvertiseNotes(String advertiseNotes) {
        this.advertiseNotes = advertiseNotes;
    }

    
    @Column(name="advertise_type")
    public Short getAdvertiseType() {
        return this.advertiseType;
    }
    
    public void setAdvertiseType(Short advertiseType) {
        this.advertiseType = advertiseType;
    }

    
    @Column(name="advertise_display")
    public Short getAdvertiseDisplay() {
        return this.advertiseDisplay;
    }
    
    public void setAdvertiseDisplay(Short advertiseDisplay) {
        this.advertiseDisplay = advertiseDisplay;
    }

    
    @Column(name="advertise_image", nullable=false, length=200)
    public String getAdvertiseImage() {
        return this.advertiseImage;
    }
    
    public void setAdvertiseImage(String advertiseImage) {
        this.advertiseImage = advertiseImage;
    }




}


