package Entities;
// Generated 31-Mar-2017 00:18:20 by Hibernate Tools 4.3.1



/**
 * TblarticleExtends generated by hbm2java
 */
public class TblarticleExtends  implements java.io.Serializable {


     private Integer aeId;
     private String aeText2001;
     private String aeText2002;
     private String aeText2003;
     private String aeText2004;
     private String aeText2005;
     private Short aeByte1;
     private Short aeByte2;
     private Short aeByte3;
     private Short aeByte4;
     private Short aeByte5;
     private Short aeShort1;
     private Short aeShort2;
     private Integer aeInt1;
     private Integer aeInt2;
     private String aeText1;
     private String aeText2;
     private String aeLongtext;
     private int aeArticleId;

    public TblarticleExtends() {
    }

	
    public TblarticleExtends(int aeArticleId) {
        this.aeArticleId = aeArticleId;
    }
    public TblarticleExtends(String aeText2001, String aeText2002, String aeText2003, String aeText2004, String aeText2005, Short aeByte1, Short aeByte2, Short aeByte3, Short aeByte4, Short aeByte5, Short aeShort1, Short aeShort2, Integer aeInt1, Integer aeInt2, String aeText1, String aeText2, String aeLongtext, int aeArticleId) {
       this.aeText2001 = aeText2001;
       this.aeText2002 = aeText2002;
       this.aeText2003 = aeText2003;
       this.aeText2004 = aeText2004;
       this.aeText2005 = aeText2005;
       this.aeByte1 = aeByte1;
       this.aeByte2 = aeByte2;
       this.aeByte3 = aeByte3;
       this.aeByte4 = aeByte4;
       this.aeByte5 = aeByte5;
       this.aeShort1 = aeShort1;
       this.aeShort2 = aeShort2;
       this.aeInt1 = aeInt1;
       this.aeInt2 = aeInt2;
       this.aeText1 = aeText1;
       this.aeText2 = aeText2;
       this.aeLongtext = aeLongtext;
       this.aeArticleId = aeArticleId;
    }
   
    public Integer getAeId() {
        return this.aeId;
    }
    
    public void setAeId(Integer aeId) {
        this.aeId = aeId;
    }
    public String getAeText2001() {
        return this.aeText2001;
    }
    
    public void setAeText2001(String aeText2001) {
        this.aeText2001 = aeText2001;
    }
    public String getAeText2002() {
        return this.aeText2002;
    }
    
    public void setAeText2002(String aeText2002) {
        this.aeText2002 = aeText2002;
    }
    public String getAeText2003() {
        return this.aeText2003;
    }
    
    public void setAeText2003(String aeText2003) {
        this.aeText2003 = aeText2003;
    }
    public String getAeText2004() {
        return this.aeText2004;
    }
    
    public void setAeText2004(String aeText2004) {
        this.aeText2004 = aeText2004;
    }
    public String getAeText2005() {
        return this.aeText2005;
    }
    
    public void setAeText2005(String aeText2005) {
        this.aeText2005 = aeText2005;
    }
    public Short getAeByte1() {
        return this.aeByte1;
    }
    
    public void setAeByte1(Short aeByte1) {
        this.aeByte1 = aeByte1;
    }
    public Short getAeByte2() {
        return this.aeByte2;
    }
    
    public void setAeByte2(Short aeByte2) {
        this.aeByte2 = aeByte2;
    }
    public Short getAeByte3() {
        return this.aeByte3;
    }
    
    public void setAeByte3(Short aeByte3) {
        this.aeByte3 = aeByte3;
    }
    public Short getAeByte4() {
        return this.aeByte4;
    }
    
    public void setAeByte4(Short aeByte4) {
        this.aeByte4 = aeByte4;
    }
    public Short getAeByte5() {
        return this.aeByte5;
    }
    
    public void setAeByte5(Short aeByte5) {
        this.aeByte5 = aeByte5;
    }
    public Short getAeShort1() {
        return this.aeShort1;
    }
    
    public void setAeShort1(Short aeShort1) {
        this.aeShort1 = aeShort1;
    }
    public Short getAeShort2() {
        return this.aeShort2;
    }
    
    public void setAeShort2(Short aeShort2) {
        this.aeShort2 = aeShort2;
    }
    public Integer getAeInt1() {
        return this.aeInt1;
    }
    
    public void setAeInt1(Integer aeInt1) {
        this.aeInt1 = aeInt1;
    }
    public Integer getAeInt2() {
        return this.aeInt2;
    }
    
    public void setAeInt2(Integer aeInt2) {
        this.aeInt2 = aeInt2;
    }
    public String getAeText1() {
        return this.aeText1;
    }
    
    public void setAeText1(String aeText1) {
        this.aeText1 = aeText1;
    }
    public String getAeText2() {
        return this.aeText2;
    }
    
    public void setAeText2(String aeText2) {
        this.aeText2 = aeText2;
    }
    public String getAeLongtext() {
        return this.aeLongtext;
    }
    
    public void setAeLongtext(String aeLongtext) {
        this.aeLongtext = aeLongtext;
    }
    public int getAeArticleId() {
        return this.aeArticleId;
    }
    
    public void setAeArticleId(int aeArticleId) {
        this.aeArticleId = aeArticleId;
    }




}


