package Entities;
// Generated Feb 10, 2017 12:03:07 AM by Hibernate Tools 4.3.1



/**
 * Tbladvertise generated by hbm2java
 */
public class Tbladvertise  implements java.io.Serializable {


     private Integer advertiseId;
     private String advertiseTitle;
     private String advertiseUrl;
     private String advertiseNotes;
     private Short advertiseType;
     private Short advertiseDisplay;
     private String advertiseImage;

    public Tbladvertise() {
    }

	
    public Tbladvertise(String advertiseTitle, String advertiseImage) {
        this.advertiseTitle = advertiseTitle;
        this.advertiseImage = advertiseImage;
    }
    public Tbladvertise(String advertiseTitle, String advertiseUrl, String advertiseNotes, Short advertiseType, Short advertiseDisplay, String advertiseImage) {
       this.advertiseTitle = advertiseTitle;
       this.advertiseUrl = advertiseUrl;
       this.advertiseNotes = advertiseNotes;
       this.advertiseType = advertiseType;
       this.advertiseDisplay = advertiseDisplay;
       this.advertiseImage = advertiseImage;
    }
   
    public Integer getAdvertiseId() {
        return this.advertiseId;
    }
    
    public void setAdvertiseId(Integer advertiseId) {
        this.advertiseId = advertiseId;
    }
    public String getAdvertiseTitle() {
        return this.advertiseTitle;
    }
    
    public void setAdvertiseTitle(String advertiseTitle) {
        this.advertiseTitle = advertiseTitle;
    }
    public String getAdvertiseUrl() {
        return this.advertiseUrl;
    }
    
    public void setAdvertiseUrl(String advertiseUrl) {
        this.advertiseUrl = advertiseUrl;
    }
    public String getAdvertiseNotes() {
        return this.advertiseNotes;
    }
    
    public void setAdvertiseNotes(String advertiseNotes) {
        this.advertiseNotes = advertiseNotes;
    }
    public Short getAdvertiseType() {
        return this.advertiseType;
    }
    
    public void setAdvertiseType(Short advertiseType) {
        this.advertiseType = advertiseType;
    }
    public Short getAdvertiseDisplay() {
        return this.advertiseDisplay;
    }
    
    public void setAdvertiseDisplay(Short advertiseDisplay) {
        this.advertiseDisplay = advertiseDisplay;
    }
    public String getAdvertiseImage() {
        return this.advertiseImage;
    }
    
    public void setAdvertiseImage(String advertiseImage) {
        this.advertiseImage = advertiseImage;
    }




}


