package Entities;
// Generated Mar 19, 2017 11:45:26 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tblaccount generated by hbm2java
 */
@Entity
@Table(name="tblaccount"
    ,catalog="motchangduong_data"
)
public class Tblaccount  implements java.io.Serializable {


     private Integer accountId;
     private int accountCustomerId;
     private Integer accountMoney;
     private Date accountActivedDate;
     private String accountNotes;
     private Integer accountCurrentMoney;
     private Short accountType;

    public Tblaccount() {
    }

	
    public Tblaccount(int accountCustomerId) {
        this.accountCustomerId = accountCustomerId;
    }
    public Tblaccount(int accountCustomerId, Integer accountMoney, Date accountActivedDate, String accountNotes, Integer accountCurrentMoney, Short accountType) {
       this.accountCustomerId = accountCustomerId;
       this.accountMoney = accountMoney;
       this.accountActivedDate = accountActivedDate;
       this.accountNotes = accountNotes;
       this.accountCurrentMoney = accountCurrentMoney;
       this.accountType = accountType;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="account_id", unique=true, nullable=false)
    public Integer getAccountId() {
        return this.accountId;
    }
    
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    
    @Column(name="account_customer_id", nullable=false)
    public int getAccountCustomerId() {
        return this.accountCustomerId;
    }
    
    public void setAccountCustomerId(int accountCustomerId) {
        this.accountCustomerId = accountCustomerId;
    }

    
    @Column(name="account_money")
    public Integer getAccountMoney() {
        return this.accountMoney;
    }
    
    public void setAccountMoney(Integer accountMoney) {
        this.accountMoney = accountMoney;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="account_actived_date", length=19)
    public Date getAccountActivedDate() {
        return this.accountActivedDate;
    }
    
    public void setAccountActivedDate(Date accountActivedDate) {
        this.accountActivedDate = accountActivedDate;
    }

    
    @Column(name="account_notes", length=65535)
    public String getAccountNotes() {
        return this.accountNotes;
    }
    
    public void setAccountNotes(String accountNotes) {
        this.accountNotes = accountNotes;
    }

    
    @Column(name="account_current_money")
    public Integer getAccountCurrentMoney() {
        return this.accountCurrentMoney;
    }
    
    public void setAccountCurrentMoney(Integer accountCurrentMoney) {
        this.accountCurrentMoney = accountCurrentMoney;
    }

    
    @Column(name="account_type")
    public Short getAccountType() {
        return this.accountType;
    }
    
    public void setAccountType(Short accountType) {
        this.accountType = accountType;
    }




}


