package Entities;
// Generated Mar 19, 2017 11:45:26 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tblcategory generated by hbm2java
 */
@Entity
@Table(name="tblcategory"
    ,catalog="motchangduong_data"
)
public class Tblcategory  implements java.io.Serializable {


     private Short categoryId;
     private String categoryName;
     private short categorySectionId;
     private String categoryNotes;
     private Date categoryCreatedDate;
     private Integer categoryCreatedAuthorId;
     private String categoryLastModified;
     private Integer categoryManagerId;
     private Boolean categoryEnable;
     private Boolean categoryDelete;
     private String categoryImage;
     private String categoryNameEn;
     private Short categoryLanguage;

    public Tblcategory() {
    }

	
    public Tblcategory(String categoryName, short categorySectionId) {
        this.categoryName = categoryName;
        this.categorySectionId = categorySectionId;
    }
    public Tblcategory(String categoryName, short categorySectionId, String categoryNotes, Date categoryCreatedDate, Integer categoryCreatedAuthorId, String categoryLastModified, Integer categoryManagerId, Boolean categoryEnable, Boolean categoryDelete, String categoryImage, String categoryNameEn, Short categoryLanguage) {
       this.categoryName = categoryName;
       this.categorySectionId = categorySectionId;
       this.categoryNotes = categoryNotes;
       this.categoryCreatedDate = categoryCreatedDate;
       this.categoryCreatedAuthorId = categoryCreatedAuthorId;
       this.categoryLastModified = categoryLastModified;
       this.categoryManagerId = categoryManagerId;
       this.categoryEnable = categoryEnable;
       this.categoryDelete = categoryDelete;
       this.categoryImage = categoryImage;
       this.categoryNameEn = categoryNameEn;
       this.categoryLanguage = categoryLanguage;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="category_id", unique=true, nullable=false)
    public Short getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(Short categoryId) {
        this.categoryId = categoryId;
    }

    
    @Column(name="category_name", nullable=false, length=200)
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    
    @Column(name="category_section_id", nullable=false)
    public short getCategorySectionId() {
        return this.categorySectionId;
    }
    
    public void setCategorySectionId(short categorySectionId) {
        this.categorySectionId = categorySectionId;
    }

    
    @Column(name="category_notes", length=65535)
    public String getCategoryNotes() {
        return this.categoryNotes;
    }
    
    public void setCategoryNotes(String categoryNotes) {
        this.categoryNotes = categoryNotes;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="category_created_date", length=19)
    public Date getCategoryCreatedDate() {
        return this.categoryCreatedDate;
    }
    
    public void setCategoryCreatedDate(Date categoryCreatedDate) {
        this.categoryCreatedDate = categoryCreatedDate;
    }

    
    @Column(name="category_created_author_id")
    public Integer getCategoryCreatedAuthorId() {
        return this.categoryCreatedAuthorId;
    }
    
    public void setCategoryCreatedAuthorId(Integer categoryCreatedAuthorId) {
        this.categoryCreatedAuthorId = categoryCreatedAuthorId;
    }

    
    @Column(name="category_last_modified", length=50)
    public String getCategoryLastModified() {
        return this.categoryLastModified;
    }
    
    public void setCategoryLastModified(String categoryLastModified) {
        this.categoryLastModified = categoryLastModified;
    }

    
    @Column(name="category_manager_id")
    public Integer getCategoryManagerId() {
        return this.categoryManagerId;
    }
    
    public void setCategoryManagerId(Integer categoryManagerId) {
        this.categoryManagerId = categoryManagerId;
    }

    
    @Column(name="category_enable")
    public Boolean getCategoryEnable() {
        return this.categoryEnable;
    }
    
    public void setCategoryEnable(Boolean categoryEnable) {
        this.categoryEnable = categoryEnable;
    }

    
    @Column(name="category_delete")
    public Boolean getCategoryDelete() {
        return this.categoryDelete;
    }
    
    public void setCategoryDelete(Boolean categoryDelete) {
        this.categoryDelete = categoryDelete;
    }

    
    @Column(name="category_image", length=200)
    public String getCategoryImage() {
        return this.categoryImage;
    }
    
    public void setCategoryImage(String categoryImage) {
        this.categoryImage = categoryImage;
    }

    
    @Column(name="category_name_en", length=200)
    public String getCategoryNameEn() {
        return this.categoryNameEn;
    }
    
    public void setCategoryNameEn(String categoryNameEn) {
        this.categoryNameEn = categoryNameEn;
    }

    
    @Column(name="category_language")
    public Short getCategoryLanguage() {
        return this.categoryLanguage;
    }
    
    public void setCategoryLanguage(Short categoryLanguage) {
        this.categoryLanguage = categoryLanguage;
    }




}


