package Entities;
// Generated 31-Mar-2017 00:18:20 by Hibernate Tools 4.3.1



/**
 * Tblcalendar generated by hbm2java
 */
public class Tblcalendar  implements java.io.Serializable {


     private Integer calendarId;
     private String calendarTitle;
     private String calendarCreatedDate;
     private String calendarFirstdateofweek;
     private String calendarFirstdateofweekLunar;
     private String calendarMon1;
     private String calendarMon2;
     private String calendarMon3;
     private String calendarTue1;
     private String calendarTue2;
     private String calendarTue3;
     private String calendarWed1;
     private String calendarWed2;
     private String calendarWed3;
     private String calendarThu1;
     private String calendarThu2;
     private String calendarThu3;
     private String calendarFri1;
     private String calendarFri2;
     private String calendarFri3;
     private String calendarSat1;
     private String calendarSat2;
     private String calendarSat3;
     private String calendarSun1;
     private String calendarSun2;
     private String calendarSun3;
     private String calendarNotesMon;
     private String calendarNotesTue;
     private String calendarNotesWed;
     private String calendarNotesThu;
     private String calendarNotesFri;
     private String calendarNotesSat;
     private String calendarNotesSun;
     private String calendarNotes;
     private Boolean calendarPriority;
     private String calendarUserName;
     private Short calendarVisited;

    public Tblcalendar() {
    }

    public Tblcalendar(String calendarTitle, String calendarCreatedDate, String calendarFirstdateofweek, String calendarFirstdateofweekLunar, String calendarMon1, String calendarMon2, String calendarMon3, String calendarTue1, String calendarTue2, String calendarTue3, String calendarWed1, String calendarWed2, String calendarWed3, String calendarThu1, String calendarThu2, String calendarThu3, String calendarFri1, String calendarFri2, String calendarFri3, String calendarSat1, String calendarSat2, String calendarSat3, String calendarSun1, String calendarSun2, String calendarSun3, String calendarNotesMon, String calendarNotesTue, String calendarNotesWed, String calendarNotesThu, String calendarNotesFri, String calendarNotesSat, String calendarNotesSun, String calendarNotes, Boolean calendarPriority, String calendarUserName, Short calendarVisited) {
       this.calendarTitle = calendarTitle;
       this.calendarCreatedDate = calendarCreatedDate;
       this.calendarFirstdateofweek = calendarFirstdateofweek;
       this.calendarFirstdateofweekLunar = calendarFirstdateofweekLunar;
       this.calendarMon1 = calendarMon1;
       this.calendarMon2 = calendarMon2;
       this.calendarMon3 = calendarMon3;
       this.calendarTue1 = calendarTue1;
       this.calendarTue2 = calendarTue2;
       this.calendarTue3 = calendarTue3;
       this.calendarWed1 = calendarWed1;
       this.calendarWed2 = calendarWed2;
       this.calendarWed3 = calendarWed3;
       this.calendarThu1 = calendarThu1;
       this.calendarThu2 = calendarThu2;
       this.calendarThu3 = calendarThu3;
       this.calendarFri1 = calendarFri1;
       this.calendarFri2 = calendarFri2;
       this.calendarFri3 = calendarFri3;
       this.calendarSat1 = calendarSat1;
       this.calendarSat2 = calendarSat2;
       this.calendarSat3 = calendarSat3;
       this.calendarSun1 = calendarSun1;
       this.calendarSun2 = calendarSun2;
       this.calendarSun3 = calendarSun3;
       this.calendarNotesMon = calendarNotesMon;
       this.calendarNotesTue = calendarNotesTue;
       this.calendarNotesWed = calendarNotesWed;
       this.calendarNotesThu = calendarNotesThu;
       this.calendarNotesFri = calendarNotesFri;
       this.calendarNotesSat = calendarNotesSat;
       this.calendarNotesSun = calendarNotesSun;
       this.calendarNotes = calendarNotes;
       this.calendarPriority = calendarPriority;
       this.calendarUserName = calendarUserName;
       this.calendarVisited = calendarVisited;
    }
   
    public Integer getCalendarId() {
        return this.calendarId;
    }
    
    public void setCalendarId(Integer calendarId) {
        this.calendarId = calendarId;
    }
    public String getCalendarTitle() {
        return this.calendarTitle;
    }
    
    public void setCalendarTitle(String calendarTitle) {
        this.calendarTitle = calendarTitle;
    }
    public String getCalendarCreatedDate() {
        return this.calendarCreatedDate;
    }
    
    public void setCalendarCreatedDate(String calendarCreatedDate) {
        this.calendarCreatedDate = calendarCreatedDate;
    }
    public String getCalendarFirstdateofweek() {
        return this.calendarFirstdateofweek;
    }
    
    public void setCalendarFirstdateofweek(String calendarFirstdateofweek) {
        this.calendarFirstdateofweek = calendarFirstdateofweek;
    }
    public String getCalendarFirstdateofweekLunar() {
        return this.calendarFirstdateofweekLunar;
    }
    
    public void setCalendarFirstdateofweekLunar(String calendarFirstdateofweekLunar) {
        this.calendarFirstdateofweekLunar = calendarFirstdateofweekLunar;
    }
    public String getCalendarMon1() {
        return this.calendarMon1;
    }
    
    public void setCalendarMon1(String calendarMon1) {
        this.calendarMon1 = calendarMon1;
    }
    public String getCalendarMon2() {
        return this.calendarMon2;
    }
    
    public void setCalendarMon2(String calendarMon2) {
        this.calendarMon2 = calendarMon2;
    }
    public String getCalendarMon3() {
        return this.calendarMon3;
    }
    
    public void setCalendarMon3(String calendarMon3) {
        this.calendarMon3 = calendarMon3;
    }
    public String getCalendarTue1() {
        return this.calendarTue1;
    }
    
    public void setCalendarTue1(String calendarTue1) {
        this.calendarTue1 = calendarTue1;
    }
    public String getCalendarTue2() {
        return this.calendarTue2;
    }
    
    public void setCalendarTue2(String calendarTue2) {
        this.calendarTue2 = calendarTue2;
    }
    public String getCalendarTue3() {
        return this.calendarTue3;
    }
    
    public void setCalendarTue3(String calendarTue3) {
        this.calendarTue3 = calendarTue3;
    }
    public String getCalendarWed1() {
        return this.calendarWed1;
    }
    
    public void setCalendarWed1(String calendarWed1) {
        this.calendarWed1 = calendarWed1;
    }
    public String getCalendarWed2() {
        return this.calendarWed2;
    }
    
    public void setCalendarWed2(String calendarWed2) {
        this.calendarWed2 = calendarWed2;
    }
    public String getCalendarWed3() {
        return this.calendarWed3;
    }
    
    public void setCalendarWed3(String calendarWed3) {
        this.calendarWed3 = calendarWed3;
    }
    public String getCalendarThu1() {
        return this.calendarThu1;
    }
    
    public void setCalendarThu1(String calendarThu1) {
        this.calendarThu1 = calendarThu1;
    }
    public String getCalendarThu2() {
        return this.calendarThu2;
    }
    
    public void setCalendarThu2(String calendarThu2) {
        this.calendarThu2 = calendarThu2;
    }
    public String getCalendarThu3() {
        return this.calendarThu3;
    }
    
    public void setCalendarThu3(String calendarThu3) {
        this.calendarThu3 = calendarThu3;
    }
    public String getCalendarFri1() {
        return this.calendarFri1;
    }
    
    public void setCalendarFri1(String calendarFri1) {
        this.calendarFri1 = calendarFri1;
    }
    public String getCalendarFri2() {
        return this.calendarFri2;
    }
    
    public void setCalendarFri2(String calendarFri2) {
        this.calendarFri2 = calendarFri2;
    }
    public String getCalendarFri3() {
        return this.calendarFri3;
    }
    
    public void setCalendarFri3(String calendarFri3) {
        this.calendarFri3 = calendarFri3;
    }
    public String getCalendarSat1() {
        return this.calendarSat1;
    }
    
    public void setCalendarSat1(String calendarSat1) {
        this.calendarSat1 = calendarSat1;
    }
    public String getCalendarSat2() {
        return this.calendarSat2;
    }
    
    public void setCalendarSat2(String calendarSat2) {
        this.calendarSat2 = calendarSat2;
    }
    public String getCalendarSat3() {
        return this.calendarSat3;
    }
    
    public void setCalendarSat3(String calendarSat3) {
        this.calendarSat3 = calendarSat3;
    }
    public String getCalendarSun1() {
        return this.calendarSun1;
    }
    
    public void setCalendarSun1(String calendarSun1) {
        this.calendarSun1 = calendarSun1;
    }
    public String getCalendarSun2() {
        return this.calendarSun2;
    }
    
    public void setCalendarSun2(String calendarSun2) {
        this.calendarSun2 = calendarSun2;
    }
    public String getCalendarSun3() {
        return this.calendarSun3;
    }
    
    public void setCalendarSun3(String calendarSun3) {
        this.calendarSun3 = calendarSun3;
    }
    public String getCalendarNotesMon() {
        return this.calendarNotesMon;
    }
    
    public void setCalendarNotesMon(String calendarNotesMon) {
        this.calendarNotesMon = calendarNotesMon;
    }
    public String getCalendarNotesTue() {
        return this.calendarNotesTue;
    }
    
    public void setCalendarNotesTue(String calendarNotesTue) {
        this.calendarNotesTue = calendarNotesTue;
    }
    public String getCalendarNotesWed() {
        return this.calendarNotesWed;
    }
    
    public void setCalendarNotesWed(String calendarNotesWed) {
        this.calendarNotesWed = calendarNotesWed;
    }
    public String getCalendarNotesThu() {
        return this.calendarNotesThu;
    }
    
    public void setCalendarNotesThu(String calendarNotesThu) {
        this.calendarNotesThu = calendarNotesThu;
    }
    public String getCalendarNotesFri() {
        return this.calendarNotesFri;
    }
    
    public void setCalendarNotesFri(String calendarNotesFri) {
        this.calendarNotesFri = calendarNotesFri;
    }
    public String getCalendarNotesSat() {
        return this.calendarNotesSat;
    }
    
    public void setCalendarNotesSat(String calendarNotesSat) {
        this.calendarNotesSat = calendarNotesSat;
    }
    public String getCalendarNotesSun() {
        return this.calendarNotesSun;
    }
    
    public void setCalendarNotesSun(String calendarNotesSun) {
        this.calendarNotesSun = calendarNotesSun;
    }
    public String getCalendarNotes() {
        return this.calendarNotes;
    }
    
    public void setCalendarNotes(String calendarNotes) {
        this.calendarNotes = calendarNotes;
    }
    public Boolean getCalendarPriority() {
        return this.calendarPriority;
    }
    
    public void setCalendarPriority(Boolean calendarPriority) {
        this.calendarPriority = calendarPriority;
    }
    public String getCalendarUserName() {
        return this.calendarUserName;
    }
    
    public void setCalendarUserName(String calendarUserName) {
        this.calendarUserName = calendarUserName;
    }
    public Short getCalendarVisited() {
        return this.calendarVisited;
    }
    
    public void setCalendarVisited(Short calendarVisited) {
        this.calendarVisited = calendarVisited;
    }




}


