package Entities;
// Generated 31-Mar-2017 00:18:20 by Hibernate Tools 4.3.1



/**
 * Tblcustomer generated by hbm2java
 */
public class Tblcustomer  implements java.io.Serializable {


     private Integer customerId;
     private String customerFullname;
     private String customerAddress;
     private String customerPhone;
     private String customerMobile;
     private String customerOffice;
     private String customerJobarea;
     private String customerNotes;
     private String customerEmail;
     private String customerIdentityCard;
     private String customerUsername;
     private String customerPassword;
     private Short customerTypeId;
     private Integer customerLogined;
     private String customerCreatedDate;
     private String customerModifiedDate;
     private Boolean customerIsactive;
     private String customerCode;
     private String customerCompany;
     private Integer customerProductId;
     private Integer customerArticleextendsId;
     private String customerIp;

    public Tblcustomer() {
    }

	
    public Tblcustomer(String customerUsername, String customerPassword) {
        this.customerUsername = customerUsername;
        this.customerPassword = customerPassword;
    }
    public Tblcustomer(String customerFullname, String customerAddress, String customerPhone, String customerMobile, String customerOffice, String customerJobarea, String customerNotes, String customerEmail, String customerIdentityCard, String customerUsername, String customerPassword, Short customerTypeId, Integer customerLogined, String customerCreatedDate, String customerModifiedDate, Boolean customerIsactive, String customerCode, String customerCompany, Integer customerProductId, Integer customerArticleextendsId, String customerIp) {
       this.customerFullname = customerFullname;
       this.customerAddress = customerAddress;
       this.customerPhone = customerPhone;
       this.customerMobile = customerMobile;
       this.customerOffice = customerOffice;
       this.customerJobarea = customerJobarea;
       this.customerNotes = customerNotes;
       this.customerEmail = customerEmail;
       this.customerIdentityCard = customerIdentityCard;
       this.customerUsername = customerUsername;
       this.customerPassword = customerPassword;
       this.customerTypeId = customerTypeId;
       this.customerLogined = customerLogined;
       this.customerCreatedDate = customerCreatedDate;
       this.customerModifiedDate = customerModifiedDate;
       this.customerIsactive = customerIsactive;
       this.customerCode = customerCode;
       this.customerCompany = customerCompany;
       this.customerProductId = customerProductId;
       this.customerArticleextendsId = customerArticleextendsId;
       this.customerIp = customerIp;
    }
   
    public Integer getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }
    public String getCustomerFullname() {
        return this.customerFullname;
    }
    
    public void setCustomerFullname(String customerFullname) {
        this.customerFullname = customerFullname;
    }
    public String getCustomerAddress() {
        return this.customerAddress;
    }
    
    public void setCustomerAddress(String customerAddress) {
        this.customerAddress = customerAddress;
    }
    public String getCustomerPhone() {
        return this.customerPhone;
    }
    
    public void setCustomerPhone(String customerPhone) {
        this.customerPhone = customerPhone;
    }
    public String getCustomerMobile() {
        return this.customerMobile;
    }
    
    public void setCustomerMobile(String customerMobile) {
        this.customerMobile = customerMobile;
    }
    public String getCustomerOffice() {
        return this.customerOffice;
    }
    
    public void setCustomerOffice(String customerOffice) {
        this.customerOffice = customerOffice;
    }
    public String getCustomerJobarea() {
        return this.customerJobarea;
    }
    
    public void setCustomerJobarea(String customerJobarea) {
        this.customerJobarea = customerJobarea;
    }
    public String getCustomerNotes() {
        return this.customerNotes;
    }
    
    public void setCustomerNotes(String customerNotes) {
        this.customerNotes = customerNotes;
    }
    public String getCustomerEmail() {
        return this.customerEmail;
    }
    
    public void setCustomerEmail(String customerEmail) {
        this.customerEmail = customerEmail;
    }
    public String getCustomerIdentityCard() {
        return this.customerIdentityCard;
    }
    
    public void setCustomerIdentityCard(String customerIdentityCard) {
        this.customerIdentityCard = customerIdentityCard;
    }
    public String getCustomerUsername() {
        return this.customerUsername;
    }
    
    public void setCustomerUsername(String customerUsername) {
        this.customerUsername = customerUsername;
    }
    public String getCustomerPassword() {
        return this.customerPassword;
    }
    
    public void setCustomerPassword(String customerPassword) {
        this.customerPassword = customerPassword;
    }
    public Short getCustomerTypeId() {
        return this.customerTypeId;
    }
    
    public void setCustomerTypeId(Short customerTypeId) {
        this.customerTypeId = customerTypeId;
    }
    public Integer getCustomerLogined() {
        return this.customerLogined;
    }
    
    public void setCustomerLogined(Integer customerLogined) {
        this.customerLogined = customerLogined;
    }
    public String getCustomerCreatedDate() {
        return this.customerCreatedDate;
    }
    
    public void setCustomerCreatedDate(String customerCreatedDate) {
        this.customerCreatedDate = customerCreatedDate;
    }
    public String getCustomerModifiedDate() {
        return this.customerModifiedDate;
    }
    
    public void setCustomerModifiedDate(String customerModifiedDate) {
        this.customerModifiedDate = customerModifiedDate;
    }
    public Boolean getCustomerIsactive() {
        return this.customerIsactive;
    }
    
    public void setCustomerIsactive(Boolean customerIsactive) {
        this.customerIsactive = customerIsactive;
    }
    public String getCustomerCode() {
        return this.customerCode;
    }
    
    public void setCustomerCode(String customerCode) {
        this.customerCode = customerCode;
    }
    public String getCustomerCompany() {
        return this.customerCompany;
    }
    
    public void setCustomerCompany(String customerCompany) {
        this.customerCompany = customerCompany;
    }
    public Integer getCustomerProductId() {
        return this.customerProductId;
    }
    
    public void setCustomerProductId(Integer customerProductId) {
        this.customerProductId = customerProductId;
    }
    public Integer getCustomerArticleextendsId() {
        return this.customerArticleextendsId;
    }
    
    public void setCustomerArticleextendsId(Integer customerArticleextendsId) {
        this.customerArticleextendsId = customerArticleextendsId;
    }
    public String getCustomerIp() {
        return this.customerIp;
    }
    
    public void setCustomerIp(String customerIp) {
        this.customerIp = customerIp;
    }




}


