package Entities;
// Generated Feb 27, 2017 11:51:07 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tblcategory generated by hbm2java
 */
public class Tblcategory  implements java.io.Serializable {


     private Short categoryId;
     private String categoryName;
     private short categorySectionId;
     private String categoryNotes;
     private Date categoryCreatedDate;
     private Integer categoryCreatedAuthorId;
     private String categoryLastModified;
     private Integer categoryManagerId;
     private Boolean categoryEnable;
     private Boolean categoryDelete;
     private String categoryImage;
     private String categoryNameEn;
     private Short categoryLanguage;

    public Tblcategory() {
    }

	
    public Tblcategory(String categoryName, short categorySectionId) {
        this.categoryName = categoryName;
        this.categorySectionId = categorySectionId;
    }
    public Tblcategory(String categoryName, short categorySectionId, String categoryNotes, Date categoryCreatedDate, Integer categoryCreatedAuthorId, String categoryLastModified, Integer categoryManagerId, Boolean categoryEnable, Boolean categoryDelete, String categoryImage, String categoryNameEn, Short categoryLanguage) {
       this.categoryName = categoryName;
       this.categorySectionId = categorySectionId;
       this.categoryNotes = categoryNotes;
       this.categoryCreatedDate = categoryCreatedDate;
       this.categoryCreatedAuthorId = categoryCreatedAuthorId;
       this.categoryLastModified = categoryLastModified;
       this.categoryManagerId = categoryManagerId;
       this.categoryEnable = categoryEnable;
       this.categoryDelete = categoryDelete;
       this.categoryImage = categoryImage;
       this.categoryNameEn = categoryNameEn;
       this.categoryLanguage = categoryLanguage;
    }
   
    public Short getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(Short categoryId) {
        this.categoryId = categoryId;
    }
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
    public short getCategorySectionId() {
        return this.categorySectionId;
    }
    
    public void setCategorySectionId(short categorySectionId) {
        this.categorySectionId = categorySectionId;
    }
    public String getCategoryNotes() {
        return this.categoryNotes;
    }
    
    public void setCategoryNotes(String categoryNotes) {
        this.categoryNotes = categoryNotes;
    }
    public Date getCategoryCreatedDate() {
        return this.categoryCreatedDate;
    }
    
    public void setCategoryCreatedDate(Date categoryCreatedDate) {
        this.categoryCreatedDate = categoryCreatedDate;
    }
    public Integer getCategoryCreatedAuthorId() {
        return this.categoryCreatedAuthorId;
    }
    
    public void setCategoryCreatedAuthorId(Integer categoryCreatedAuthorId) {
        this.categoryCreatedAuthorId = categoryCreatedAuthorId;
    }
    public String getCategoryLastModified() {
        return this.categoryLastModified;
    }
    
    public void setCategoryLastModified(String categoryLastModified) {
        this.categoryLastModified = categoryLastModified;
    }
    public Integer getCategoryManagerId() {
        return this.categoryManagerId;
    }
    
    public void setCategoryManagerId(Integer categoryManagerId) {
        this.categoryManagerId = categoryManagerId;
    }
    public Boolean getCategoryEnable() {
        return this.categoryEnable;
    }
    
    public void setCategoryEnable(Boolean categoryEnable) {
        this.categoryEnable = categoryEnable;
    }
    public Boolean getCategoryDelete() {
        return this.categoryDelete;
    }
    
    public void setCategoryDelete(Boolean categoryDelete) {
        this.categoryDelete = categoryDelete;
    }
    public String getCategoryImage() {
        return this.categoryImage;
    }
    
    public void setCategoryImage(String categoryImage) {
        this.categoryImage = categoryImage;
    }
    public String getCategoryNameEn() {
        return this.categoryNameEn;
    }
    
    public void setCategoryNameEn(String categoryNameEn) {
        this.categoryNameEn = categoryNameEn;
    }
    public Short getCategoryLanguage() {
        return this.categoryLanguage;
    }
    
    public void setCategoryLanguage(Short categoryLanguage) {
        this.categoryLanguage = categoryLanguage;
    }




}


