package Entities;
// Generated 31-Mar-2017 00:18:20 by Hibernate Tools 4.3.1



/**
 * Tblfeedback generated by hbm2java
 */
public class Tblfeedback  implements java.io.Serializable {


     private Integer feedbackId;
     private String feedbackTitle;
     private String feedbackContent;
     private String feedbackFullname;
     private String feedbackAddress;
     private String feedbackEmail;
     private String feedbackPhone;
     private Integer feedbackProductId;
     private String feedbackCreatedDate;
     private Boolean feedbackView;
     private String feedbackCompany;

    public Tblfeedback() {
    }

	
    public Tblfeedback(String feedbackContent, String feedbackFullname, String feedbackEmail, String feedbackCreatedDate) {
        this.feedbackContent = feedbackContent;
        this.feedbackFullname = feedbackFullname;
        this.feedbackEmail = feedbackEmail;
        this.feedbackCreatedDate = feedbackCreatedDate;
    }
    public Tblfeedback(String feedbackTitle, String feedbackContent, String feedbackFullname, String feedbackAddress, String feedbackEmail, String feedbackPhone, Integer feedbackProductId, String feedbackCreatedDate, Boolean feedbackView, String feedbackCompany) {
       this.feedbackTitle = feedbackTitle;
       this.feedbackContent = feedbackContent;
       this.feedbackFullname = feedbackFullname;
       this.feedbackAddress = feedbackAddress;
       this.feedbackEmail = feedbackEmail;
       this.feedbackPhone = feedbackPhone;
       this.feedbackProductId = feedbackProductId;
       this.feedbackCreatedDate = feedbackCreatedDate;
       this.feedbackView = feedbackView;
       this.feedbackCompany = feedbackCompany;
    }
   
    public Integer getFeedbackId() {
        return this.feedbackId;
    }
    
    public void setFeedbackId(Integer feedbackId) {
        this.feedbackId = feedbackId;
    }
    public String getFeedbackTitle() {
        return this.feedbackTitle;
    }
    
    public void setFeedbackTitle(String feedbackTitle) {
        this.feedbackTitle = feedbackTitle;
    }
    public String getFeedbackContent() {
        return this.feedbackContent;
    }
    
    public void setFeedbackContent(String feedbackContent) {
        this.feedbackContent = feedbackContent;
    }
    public String getFeedbackFullname() {
        return this.feedbackFullname;
    }
    
    public void setFeedbackFullname(String feedbackFullname) {
        this.feedbackFullname = feedbackFullname;
    }
    public String getFeedbackAddress() {
        return this.feedbackAddress;
    }
    
    public void setFeedbackAddress(String feedbackAddress) {
        this.feedbackAddress = feedbackAddress;
    }
    public String getFeedbackEmail() {
        return this.feedbackEmail;
    }
    
    public void setFeedbackEmail(String feedbackEmail) {
        this.feedbackEmail = feedbackEmail;
    }
    public String getFeedbackPhone() {
        return this.feedbackPhone;
    }
    
    public void setFeedbackPhone(String feedbackPhone) {
        this.feedbackPhone = feedbackPhone;
    }
    public Integer getFeedbackProductId() {
        return this.feedbackProductId;
    }
    
    public void setFeedbackProductId(Integer feedbackProductId) {
        this.feedbackProductId = feedbackProductId;
    }
    public String getFeedbackCreatedDate() {
        return this.feedbackCreatedDate;
    }
    
    public void setFeedbackCreatedDate(String feedbackCreatedDate) {
        this.feedbackCreatedDate = feedbackCreatedDate;
    }
    public Boolean getFeedbackView() {
        return this.feedbackView;
    }
    
    public void setFeedbackView(Boolean feedbackView) {
        this.feedbackView = feedbackView;
    }
    public String getFeedbackCompany() {
        return this.feedbackCompany;
    }
    
    public void setFeedbackCompany(String feedbackCompany) {
        this.feedbackCompany = feedbackCompany;
    }




}


