package Entities;
// Generated Mar 19, 2017 11:45:26 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tblfeedback generated by hbm2java
 */
@Entity
@Table(name="tblfeedback"
    ,catalog="motchangduong_data"
)
public class Tblfeedback  implements java.io.Serializable {


     private Integer feedbackId;
     private String feedbackTitle;
     private String feedbackContent;
     private String feedbackFullname;
     private String feedbackAddress;
     private String feedbackEmail;
     private String feedbackPhone;
     private Integer feedbackProductId;
     private Date feedbackCreatedDate;
     private Boolean feedbackView;
     private String feedbackCompany;

    public Tblfeedback() {
    }

	
    public Tblfeedback(String feedbackContent, String feedbackFullname, String feedbackEmail) {
        this.feedbackContent = feedbackContent;
        this.feedbackFullname = feedbackFullname;
        this.feedbackEmail = feedbackEmail;
    }
    public Tblfeedback(String feedbackTitle, String feedbackContent, String feedbackFullname, String feedbackAddress, String feedbackEmail, String feedbackPhone, Integer feedbackProductId, Date feedbackCreatedDate, Boolean feedbackView, String feedbackCompany) {
       this.feedbackTitle = feedbackTitle;
       this.feedbackContent = feedbackContent;
       this.feedbackFullname = feedbackFullname;
       this.feedbackAddress = feedbackAddress;
       this.feedbackEmail = feedbackEmail;
       this.feedbackPhone = feedbackPhone;
       this.feedbackProductId = feedbackProductId;
       this.feedbackCreatedDate = feedbackCreatedDate;
       this.feedbackView = feedbackView;
       this.feedbackCompany = feedbackCompany;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="feedback_id", unique=true, nullable=false)
    public Integer getFeedbackId() {
        return this.feedbackId;
    }
    
    public void setFeedbackId(Integer feedbackId) {
        this.feedbackId = feedbackId;
    }

    
    @Column(name="feedback_title", length=200)
    public String getFeedbackTitle() {
        return this.feedbackTitle;
    }
    
    public void setFeedbackTitle(String feedbackTitle) {
        this.feedbackTitle = feedbackTitle;
    }

    
    @Column(name="feedback_content", nullable=false, length=65535)
    public String getFeedbackContent() {
        return this.feedbackContent;
    }
    
    public void setFeedbackContent(String feedbackContent) {
        this.feedbackContent = feedbackContent;
    }

    
    @Column(name="feedback_fullname", nullable=false, length=100)
    public String getFeedbackFullname() {
        return this.feedbackFullname;
    }
    
    public void setFeedbackFullname(String feedbackFullname) {
        this.feedbackFullname = feedbackFullname;
    }

    
    @Column(name="feedback_address", length=200)
    public String getFeedbackAddress() {
        return this.feedbackAddress;
    }
    
    public void setFeedbackAddress(String feedbackAddress) {
        this.feedbackAddress = feedbackAddress;
    }

    
    @Column(name="feedback_email", nullable=false, length=100)
    public String getFeedbackEmail() {
        return this.feedbackEmail;
    }
    
    public void setFeedbackEmail(String feedbackEmail) {
        this.feedbackEmail = feedbackEmail;
    }

    
    @Column(name="feedback_phone", length=45)
    public String getFeedbackPhone() {
        return this.feedbackPhone;
    }
    
    public void setFeedbackPhone(String feedbackPhone) {
        this.feedbackPhone = feedbackPhone;
    }

    
    @Column(name="feedback_product_id")
    public Integer getFeedbackProductId() {
        return this.feedbackProductId;
    }
    
    public void setFeedbackProductId(Integer feedbackProductId) {
        this.feedbackProductId = feedbackProductId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="feedback_created_date", length=19)
    public Date getFeedbackCreatedDate() {
        return this.feedbackCreatedDate;
    }
    
    public void setFeedbackCreatedDate(Date feedbackCreatedDate) {
        this.feedbackCreatedDate = feedbackCreatedDate;
    }

    
    @Column(name="feedback_view")
    public Boolean getFeedbackView() {
        return this.feedbackView;
    }
    
    public void setFeedbackView(Boolean feedbackView) {
        this.feedbackView = feedbackView;
    }

    
    @Column(name="feedback_company", length=200)
    public String getFeedbackCompany() {
        return this.feedbackCompany;
    }
    
    public void setFeedbackCompany(String feedbackCompany) {
        this.feedbackCompany = feedbackCompany;
    }




}


