package Entities;
// Generated Mar 19, 2017 11:45:26 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tblimage generated by hbm2java
 */
@Entity
@Table(name="tblimage"
    ,catalog="motchangduong_data"
)
public class Tblimage  implements java.io.Serializable {


     private Integer imageId;
     private String imageUrl;
     private Integer imageAlbumId;
     private Integer imageCategoryId;
     private Integer imageSectionId;
     private Date imageCreatedDate;

    public Tblimage() {
    }

    public Tblimage(String imageUrl, Integer imageAlbumId, Integer imageCategoryId, Integer imageSectionId, Date imageCreatedDate) {
       this.imageUrl = imageUrl;
       this.imageAlbumId = imageAlbumId;
       this.imageCategoryId = imageCategoryId;
       this.imageSectionId = imageSectionId;
       this.imageCreatedDate = imageCreatedDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="image_id", unique=true, nullable=false)
    public Integer getImageId() {
        return this.imageId;
    }
    
    public void setImageId(Integer imageId) {
        this.imageId = imageId;
    }

    
    @Column(name="image_url", length=200)
    public String getImageUrl() {
        return this.imageUrl;
    }
    
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    
    @Column(name="image_album_id")
    public Integer getImageAlbumId() {
        return this.imageAlbumId;
    }
    
    public void setImageAlbumId(Integer imageAlbumId) {
        this.imageAlbumId = imageAlbumId;
    }

    
    @Column(name="image_category_id")
    public Integer getImageCategoryId() {
        return this.imageCategoryId;
    }
    
    public void setImageCategoryId(Integer imageCategoryId) {
        this.imageCategoryId = imageCategoryId;
    }

    
    @Column(name="image_section_id")
    public Integer getImageSectionId() {
        return this.imageSectionId;
    }
    
    public void setImageSectionId(Integer imageSectionId) {
        this.imageSectionId = imageSectionId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="image_created_date", length=19)
    public Date getImageCreatedDate() {
        return this.imageCreatedDate;
    }
    
    public void setImageCreatedDate(Date imageCreatedDate) {
        this.imageCreatedDate = imageCreatedDate;
    }




}


