package Entities;
// Generated 31-Mar-2017 00:18:20 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tblimage generated by hbm2java
 */
public class Tblimage  implements java.io.Serializable {


     private Integer imageId;
     private String imageUrl;
     private Integer imageAlbumId;
     private Integer imageCategoryId;
     private Integer imageSectionId;
     private Date imageCreatedDate;

    public Tblimage() {
    }

    public Tblimage(String imageUrl, Integer imageAlbumId, Integer imageCategoryId, Integer imageSectionId, Date imageCreatedDate) {
       this.imageUrl = imageUrl;
       this.imageAlbumId = imageAlbumId;
       this.imageCategoryId = imageCategoryId;
       this.imageSectionId = imageSectionId;
       this.imageCreatedDate = imageCreatedDate;
    }
   
    public Integer getImageId() {
        return this.imageId;
    }
    
    public void setImageId(Integer imageId) {
        this.imageId = imageId;
    }
    public String getImageUrl() {
        return this.imageUrl;
    }
    
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }
    public Integer getImageAlbumId() {
        return this.imageAlbumId;
    }
    
    public void setImageAlbumId(Integer imageAlbumId) {
        this.imageAlbumId = imageAlbumId;
    }
    public Integer getImageCategoryId() {
        return this.imageCategoryId;
    }
    
    public void setImageCategoryId(Integer imageCategoryId) {
        this.imageCategoryId = imageCategoryId;
    }
    public Integer getImageSectionId() {
        return this.imageSectionId;
    }
    
    public void setImageSectionId(Integer imageSectionId) {
        this.imageSectionId = imageSectionId;
    }
    public Date getImageCreatedDate() {
        return this.imageCreatedDate;
    }
    
    public void setImageCreatedDate(Date imageCreatedDate) {
        this.imageCreatedDate = imageCreatedDate;
    }




}


