package Entities;
// Generated Mar 19, 2017 11:45:26 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tbllog generated by hbm2java
 */
@Entity
@Table(name="tbllog"
    ,catalog="motchangduong_data"
)
public class Tbllog  implements java.io.Serializable {


     private Integer logId;
     private String logName;
     private Short logUserPermission;
     private Date logDate;
     private String logUserName;
     private Short logAction;
     private Short logPosition;

    public Tbllog() {
    }

	
    public Tbllog(String logName) {
        this.logName = logName;
    }
    public Tbllog(String logName, Short logUserPermission, Date logDate, String logUserName, Short logAction, Short logPosition) {
       this.logName = logName;
       this.logUserPermission = logUserPermission;
       this.logDate = logDate;
       this.logUserName = logUserName;
       this.logAction = logAction;
       this.logPosition = logPosition;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="log_id", unique=true, nullable=false)
    public Integer getLogId() {
        return this.logId;
    }
    
    public void setLogId(Integer logId) {
        this.logId = logId;
    }

    
    @Column(name="log_name", nullable=false, length=65535)
    public String getLogName() {
        return this.logName;
    }
    
    public void setLogName(String logName) {
        this.logName = logName;
    }

    
    @Column(name="log_user_permission")
    public Short getLogUserPermission() {
        return this.logUserPermission;
    }
    
    public void setLogUserPermission(Short logUserPermission) {
        this.logUserPermission = logUserPermission;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="log_date", length=19)
    public Date getLogDate() {
        return this.logDate;
    }
    
    public void setLogDate(Date logDate) {
        this.logDate = logDate;
    }

    
    @Column(name="log_user_name", length=45)
    public String getLogUserName() {
        return this.logUserName;
    }
    
    public void setLogUserName(String logUserName) {
        this.logUserName = logUserName;
    }

    
    @Column(name="log_action")
    public Short getLogAction() {
        return this.logAction;
    }
    
    public void setLogAction(Short logAction) {
        this.logAction = logAction;
    }

    
    @Column(name="log_position")
    public Short getLogPosition() {
        return this.logPosition;
    }
    
    public void setLogPosition(Short logPosition) {
        this.logPosition = logPosition;
    }




}


