package Entities;
// Generated Mar 19, 2017 11:45:26 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tbllabel generated by hbm2java
 */
@Entity
@Table(name="tbllabel"
    ,catalog="motchangduong_data"
)
public class Tbllabel  implements java.io.Serializable {


     private Integer labelId;
     private String labelTitle;
     private String labelInfors;
     private String labelInforsEn;
     private String labelNotes;

    public Tbllabel() {
    }

    public Tbllabel(String labelTitle, String labelInfors, String labelInforsEn, String labelNotes) {
       this.labelTitle = labelTitle;
       this.labelInfors = labelInfors;
       this.labelInforsEn = labelInforsEn;
       this.labelNotes = labelNotes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="label_id", unique=true, nullable=false)
    public Integer getLabelId() {
        return this.labelId;
    }
    
    public void setLabelId(Integer labelId) {
        this.labelId = labelId;
    }

    
    @Column(name="label_title", length=200)
    public String getLabelTitle() {
        return this.labelTitle;
    }
    
    public void setLabelTitle(String labelTitle) {
        this.labelTitle = labelTitle;
    }

    
    @Column(name="label_infors", length=65535)
    public String getLabelInfors() {
        return this.labelInfors;
    }
    
    public void setLabelInfors(String labelInfors) {
        this.labelInfors = labelInfors;
    }

    
    @Column(name="label_infors_en", length=65535)
    public String getLabelInforsEn() {
        return this.labelInforsEn;
    }
    
    public void setLabelInforsEn(String labelInforsEn) {
        this.labelInforsEn = labelInforsEn;
    }

    
    @Column(name="label_notes", length=65535)
    public String getLabelNotes() {
        return this.labelNotes;
    }
    
    public void setLabelNotes(String labelNotes) {
        this.labelNotes = labelNotes;
    }




}


