package Entities;
// Generated Mar 19, 2017 11:45:26 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tblparameter generated by hbm2java
 */
@Entity
@Table(name="tblparameter"
    ,catalog="motchangduong_data"
)
public class Tblparameter  implements java.io.Serializable {


     private Integer paraId;
     private String paraValue;
     private String paraContent;
     private String paraStatus;
     private String paraCode;
     private Date paraCreatDate;
     private Date paraEditDate;
     private String paraIsdelete;

    public Tblparameter() {
    }

    public Tblparameter(String paraValue, String paraContent, String paraStatus, String paraCode, Date paraCreatDate, Date paraEditDate, String paraIsdelete) {
       this.paraValue = paraValue;
       this.paraContent = paraContent;
       this.paraStatus = paraStatus;
       this.paraCode = paraCode;
       this.paraCreatDate = paraCreatDate;
       this.paraEditDate = paraEditDate;
       this.paraIsdelete = paraIsdelete;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="para_id", unique=true, nullable=false)
    public Integer getParaId() {
        return this.paraId;
    }
    
    public void setParaId(Integer paraId) {
        this.paraId = paraId;
    }

    
    @Column(name="para_value", length=200)
    public String getParaValue() {
        return this.paraValue;
    }
    
    public void setParaValue(String paraValue) {
        this.paraValue = paraValue;
    }

    
    @Column(name="para_content", length=500)
    public String getParaContent() {
        return this.paraContent;
    }
    
    public void setParaContent(String paraContent) {
        this.paraContent = paraContent;
    }

    
    @Column(name="para_status", length=45)
    public String getParaStatus() {
        return this.paraStatus;
    }
    
    public void setParaStatus(String paraStatus) {
        this.paraStatus = paraStatus;
    }

    
    @Column(name="para_code", length=45)
    public String getParaCode() {
        return this.paraCode;
    }
    
    public void setParaCode(String paraCode) {
        this.paraCode = paraCode;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="para_creat_date", length=19)
    public Date getParaCreatDate() {
        return this.paraCreatDate;
    }
    
    public void setParaCreatDate(Date paraCreatDate) {
        this.paraCreatDate = paraCreatDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="para_edit_date", length=19)
    public Date getParaEditDate() {
        return this.paraEditDate;
    }
    
    public void setParaEditDate(Date paraEditDate) {
        this.paraEditDate = paraEditDate;
    }

    
    @Column(name="para_isdelete", length=45)
    public String getParaIsdelete() {
        return this.paraIsdelete;
    }
    
    public void setParaIsdelete(String paraIsdelete) {
        this.paraIsdelete = paraIsdelete;
    }




}


