package Entities;
// Generated 31-Mar-2017 00:18:20 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tblparameter generated by hbm2java
 */
public class Tblparameter  implements java.io.Serializable {


     private Integer paraId;
     private String paraCode;
     private String paraValue;
     private String paraContent;
     private String paraStatus;
     private String paraIsDelete;
     private Date paraCreatDate;
     private Date paraEditDate;

    public Tblparameter() {
    }

    public Tblparameter(String paraCode, String paraValue, String paraContent, String paraStatus, String paraIsDelete, Date paraCreatDate, Date paraEditDate) {
       this.paraCode = paraCode;
       this.paraValue = paraValue;
       this.paraContent = paraContent;
       this.paraStatus = paraStatus;
       this.paraIsDelete = paraIsDelete;
       this.paraCreatDate = paraCreatDate;
       this.paraEditDate = paraEditDate;
    }
   
    public Integer getParaId() {
        return this.paraId;
    }
    
    public void setParaId(Integer paraId) {
        this.paraId = paraId;
    }
    public String getParaCode() {
        return this.paraCode;
    }
    
    public void setParaCode(String paraCode) {
        this.paraCode = paraCode;
    }
    public String getParaValue() {
        return this.paraValue;
    }
    
    public void setParaValue(String paraValue) {
        this.paraValue = paraValue;
    }
    public String getParaContent() {
        return this.paraContent;
    }
    
    public void setParaContent(String paraContent) {
        this.paraContent = paraContent;
    }
    public String getParaStatus() {
        return this.paraStatus;
    }
    
    public void setParaStatus(String paraStatus) {
        this.paraStatus = paraStatus;
    }
    public String getParaIsDelete() {
        return this.paraIsDelete;
    }
    
    public void setParaIsDelete(String paraIsDelete) {
        this.paraIsDelete = paraIsDelete;
    }
    public Date getParaCreatDate() {
        return this.paraCreatDate;
    }
    
    public void setParaCreatDate(Date paraCreatDate) {
        this.paraCreatDate = paraCreatDate;
    }
    public Date getParaEditDate() {
        return this.paraEditDate;
    }
    
    public void setParaEditDate(Date paraEditDate) {
        this.paraEditDate = paraEditDate;
    }




}


