package Entities;
// Generated Mar 19, 2017 11:45:26 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tblsection generated by hbm2java
 */
@Entity
@Table(name="tblsection"
    ,catalog="motchangduong_data"
)
public class Tblsection  implements java.io.Serializable {


     private Short sectionId;
     private String sectionName;
     private String sectionNotes;
     private Date sectionCreatedDate;
     private Integer sectionManagerId;
     private Boolean sectionEnable;
     private Boolean sectionDelete;
     private String sectionLastModified;
     private Integer sectionCreatedAuthorId;
     private String sectionNameEn;
     private Short sectionLanguage;

    public Tblsection() {
    }

	
    public Tblsection(String sectionName) {
        this.sectionName = sectionName;
    }
    public Tblsection(String sectionName, String sectionNotes, Date sectionCreatedDate, Integer sectionManagerId, Boolean sectionEnable, Boolean sectionDelete, String sectionLastModified, Integer sectionCreatedAuthorId, String sectionNameEn, Short sectionLanguage) {
       this.sectionName = sectionName;
       this.sectionNotes = sectionNotes;
       this.sectionCreatedDate = sectionCreatedDate;
       this.sectionManagerId = sectionManagerId;
       this.sectionEnable = sectionEnable;
       this.sectionDelete = sectionDelete;
       this.sectionLastModified = sectionLastModified;
       this.sectionCreatedAuthorId = sectionCreatedAuthorId;
       this.sectionNameEn = sectionNameEn;
       this.sectionLanguage = sectionLanguage;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="section_id", unique=true, nullable=false)
    public Short getSectionId() {
        return this.sectionId;
    }
    
    public void setSectionId(Short sectionId) {
        this.sectionId = sectionId;
    }

    
    @Column(name="section_name", nullable=false, length=200)
    public String getSectionName() {
        return this.sectionName;
    }
    
    public void setSectionName(String sectionName) {
        this.sectionName = sectionName;
    }

    
    @Column(name="section_notes", length=65535)
    public String getSectionNotes() {
        return this.sectionNotes;
    }
    
    public void setSectionNotes(String sectionNotes) {
        this.sectionNotes = sectionNotes;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="section_created_date", length=19)
    public Date getSectionCreatedDate() {
        return this.sectionCreatedDate;
    }
    
    public void setSectionCreatedDate(Date sectionCreatedDate) {
        this.sectionCreatedDate = sectionCreatedDate;
    }

    
    @Column(name="section_manager_id")
    public Integer getSectionManagerId() {
        return this.sectionManagerId;
    }
    
    public void setSectionManagerId(Integer sectionManagerId) {
        this.sectionManagerId = sectionManagerId;
    }

    
    @Column(name="section_enable")
    public Boolean getSectionEnable() {
        return this.sectionEnable;
    }
    
    public void setSectionEnable(Boolean sectionEnable) {
        this.sectionEnable = sectionEnable;
    }

    
    @Column(name="section_delete")
    public Boolean getSectionDelete() {
        return this.sectionDelete;
    }
    
    public void setSectionDelete(Boolean sectionDelete) {
        this.sectionDelete = sectionDelete;
    }

    
    @Column(name="section_last_modified", length=50)
    public String getSectionLastModified() {
        return this.sectionLastModified;
    }
    
    public void setSectionLastModified(String sectionLastModified) {
        this.sectionLastModified = sectionLastModified;
    }

    
    @Column(name="section_created_author_id")
    public Integer getSectionCreatedAuthorId() {
        return this.sectionCreatedAuthorId;
    }
    
    public void setSectionCreatedAuthorId(Integer sectionCreatedAuthorId) {
        this.sectionCreatedAuthorId = sectionCreatedAuthorId;
    }

    
    @Column(name="section_name_en", length=200)
    public String getSectionNameEn() {
        return this.sectionNameEn;
    }
    
    public void setSectionNameEn(String sectionNameEn) {
        this.sectionNameEn = sectionNameEn;
    }

    
    @Column(name="section_language")
    public Short getSectionLanguage() {
        return this.sectionLanguage;
    }
    
    public void setSectionLanguage(Short sectionLanguage) {
        this.sectionLanguage = sectionLanguage;
    }




}


