package Entities;
// Generated Mar 19, 2017 11:45:26 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tblstatistic generated by hbm2java
 */
@Entity
@Table(name="tblstatistic"
    ,catalog="motchangduong_data"
)
public class Tblstatistic  implements java.io.Serializable {


     private Integer statisticId;
     private Date statisticCurrentDate;
     private Integer statisticVisited;

    public Tblstatistic() {
    }

    public Tblstatistic(Date statisticCurrentDate, Integer statisticVisited) {
       this.statisticCurrentDate = statisticCurrentDate;
       this.statisticVisited = statisticVisited;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="statistic_id", unique=true, nullable=false)
    public Integer getStatisticId() {
        return this.statisticId;
    }
    
    public void setStatisticId(Integer statisticId) {
        this.statisticId = statisticId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="statistic_current_date", length=19)
    public Date getStatisticCurrentDate() {
        return this.statisticCurrentDate;
    }
    
    public void setStatisticCurrentDate(Date statisticCurrentDate) {
        this.statisticCurrentDate = statisticCurrentDate;
    }

    
    @Column(name="statistic_visited")
    public Integer getStatisticVisited() {
        return this.statisticVisited;
    }
    
    public void setStatisticVisited(Integer statisticVisited) {
        this.statisticVisited = statisticVisited;
    }




}


