package Entities;
// Generated 31-Mar-2017 00:18:20 by Hibernate Tools 4.3.1



/**
 * Tblstatistic generated by hbm2java
 */
public class Tblstatistic  implements java.io.Serializable {


     private Integer statisticId;
     private String statisticCurrentDate;
     private Integer statisticVisited;

    public Tblstatistic() {
    }

	
    public Tblstatistic(String statisticCurrentDate) {
        this.statisticCurrentDate = statisticCurrentDate;
    }
    public Tblstatistic(String statisticCurrentDate, Integer statisticVisited) {
       this.statisticCurrentDate = statisticCurrentDate;
       this.statisticVisited = statisticVisited;
    }
   
    public Integer getStatisticId() {
        return this.statisticId;
    }
    
    public void setStatisticId(Integer statisticId) {
        this.statisticId = statisticId;
    }
    public String getStatisticCurrentDate() {
        return this.statisticCurrentDate;
    }
    
    public void setStatisticCurrentDate(String statisticCurrentDate) {
        this.statisticCurrentDate = statisticCurrentDate;
    }
    public Integer getStatisticVisited() {
        return this.statisticVisited;
    }
    
    public void setStatisticVisited(Integer statisticVisited) {
        this.statisticVisited = statisticVisited;
    }




}


