package Entities;
// Generated Feb 27, 2017 11:51:07 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tblstatistic generated by hbm2java
 */
public class Tblstatistic  implements java.io.Serializable {


     private Integer statisticId;
     private Date statisticCurrentDate;
     private Integer statisticVisited;

    public Tblstatistic() {
    }

    public Tblstatistic(Date statisticCurrentDate, Integer statisticVisited) {
       this.statisticCurrentDate = statisticCurrentDate;
       this.statisticVisited = statisticVisited;
    }
   
    public Integer getStatisticId() {
        return this.statisticId;
    }
    
    public void setStatisticId(Integer statisticId) {
        this.statisticId = statisticId;
    }
    public Date getStatisticCurrentDate() {
        return this.statisticCurrentDate;
    }
    
    public void setStatisticCurrentDate(Date statisticCurrentDate) {
        this.statisticCurrentDate = statisticCurrentDate;
    }
    public Integer getStatisticVisited() {
        return this.statisticVisited;
    }
    
    public void setStatisticVisited(Integer statisticVisited) {
        this.statisticVisited = statisticVisited;
    }




}


