package Entities;
// Generated Feb 10, 2017 12:03:07 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tblsection generated by hbm2java
 */
public class Tblsection  implements java.io.Serializable {


     private Short sectionId;
     private String sectionName;
     private String sectionNotes;
     private Date sectionCreatedDate;
     private Integer sectionManagerId;
     private Boolean sectionEnable;
     private Boolean sectionDelete;
     private String sectionLastModified;
     private Integer sectionCreatedAuthorId;
     private String sectionNameEn;
     private Short sectionLanguage;

    public Tblsection() {
    }

	
    public Tblsection(String sectionName) {
        this.sectionName = sectionName;
    }
    public Tblsection(String sectionName, String sectionNotes, Date sectionCreatedDate, Integer sectionManagerId, Boolean sectionEnable, Boolean sectionDelete, String sectionLastModified, Integer sectionCreatedAuthorId, String sectionNameEn, Short sectionLanguage) {
       this.sectionName = sectionName;
       this.sectionNotes = sectionNotes;
       this.sectionCreatedDate = sectionCreatedDate;
       this.sectionManagerId = sectionManagerId;
       this.sectionEnable = sectionEnable;
       this.sectionDelete = sectionDelete;
       this.sectionLastModified = sectionLastModified;
       this.sectionCreatedAuthorId = sectionCreatedAuthorId;
       this.sectionNameEn = sectionNameEn;
       this.sectionLanguage = sectionLanguage;
    }
   
    public Short getSectionId() {
        return this.sectionId;
    }
    
    public void setSectionId(Short sectionId) {
        this.sectionId = sectionId;
    }
    public String getSectionName() {
        return this.sectionName;
    }
    
    public void setSectionName(String sectionName) {
        this.sectionName = sectionName;
    }
    public String getSectionNotes() {
        return this.sectionNotes;
    }
    
    public void setSectionNotes(String sectionNotes) {
        this.sectionNotes = sectionNotes;
    }
    public Date getSectionCreatedDate() {
        return this.sectionCreatedDate;
    }
    
    public void setSectionCreatedDate(Date sectionCreatedDate) {
        this.sectionCreatedDate = sectionCreatedDate;
    }
    public Integer getSectionManagerId() {
        return this.sectionManagerId;
    }
    
    public void setSectionManagerId(Integer sectionManagerId) {
        this.sectionManagerId = sectionManagerId;
    }
    public Boolean getSectionEnable() {
        return this.sectionEnable;
    }
    
    public void setSectionEnable(Boolean sectionEnable) {
        this.sectionEnable = sectionEnable;
    }
    public Boolean getSectionDelete() {
        return this.sectionDelete;
    }
    
    public void setSectionDelete(Boolean sectionDelete) {
        this.sectionDelete = sectionDelete;
    }
    public String getSectionLastModified() {
        return this.sectionLastModified;
    }
    
    public void setSectionLastModified(String sectionLastModified) {
        this.sectionLastModified = sectionLastModified;
    }
    public Integer getSectionCreatedAuthorId() {
        return this.sectionCreatedAuthorId;
    }
    
    public void setSectionCreatedAuthorId(Integer sectionCreatedAuthorId) {
        this.sectionCreatedAuthorId = sectionCreatedAuthorId;
    }
    public String getSectionNameEn() {
        return this.sectionNameEn;
    }
    
    public void setSectionNameEn(String sectionNameEn) {
        this.sectionNameEn = sectionNameEn;
    }
    public Short getSectionLanguage() {
        return this.sectionLanguage;
    }
    
    public void setSectionLanguage(Short sectionLanguage) {
        this.sectionLanguage = sectionLanguage;
    }




}


