package Entities;
// Generated Mar 19, 2017 11:45:26 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tbluser generated by hbm2java
 */
@Entity
@Table(name="tbluser"
    ,catalog="motchangduong_data"
)
public class Tbluser  implements java.io.Serializable {


     private Integer userId;
     private String userName;
     private String userPass;
     private String userFullname;
     private String userBirthday;
     private String userMobilephone;
     private String userHomephone;
     private String userOfficephone;
     private String userEmail;
     private String userAddress;
     private String userJobarea;
     private String userJob;
     private String userPosition;
     private Short userApplyyear;
     private Short userPermission;
     private String userNotes;
     private String userRoles;
     private Integer userLogined;
     private Date userCreatedDate;
     private Date userEditedDate;
     private String userStatus;

    public Tbluser() {
    }

    public Tbluser(String userName, String userPass, String userFullname, String userBirthday, String userMobilephone, String userHomephone, String userOfficephone, String userEmail, String userAddress, String userJobarea, String userJob, String userPosition, Short userApplyyear, Short userPermission, String userNotes, String userRoles, Integer userLogined, Date userCreatedDate, Date userEditedDate, String userStatus) {
       this.userName = userName;
       this.userPass = userPass;
       this.userFullname = userFullname;
       this.userBirthday = userBirthday;
       this.userMobilephone = userMobilephone;
       this.userHomephone = userHomephone;
       this.userOfficephone = userOfficephone;
       this.userEmail = userEmail;
       this.userAddress = userAddress;
       this.userJobarea = userJobarea;
       this.userJob = userJob;
       this.userPosition = userPosition;
       this.userApplyyear = userApplyyear;
       this.userPermission = userPermission;
       this.userNotes = userNotes;
       this.userRoles = userRoles;
       this.userLogined = userLogined;
       this.userCreatedDate = userCreatedDate;
       this.userEditedDate = userEditedDate;
       this.userStatus = userStatus;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="user_id", unique=true, nullable=false)
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    
    @Column(name="user_name", length=100)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="user_pass", length=100)
    public String getUserPass() {
        return this.userPass;
    }
    
    public void setUserPass(String userPass) {
        this.userPass = userPass;
    }

    
    @Column(name="user_fullname", length=45)
    public String getUserFullname() {
        return this.userFullname;
    }
    
    public void setUserFullname(String userFullname) {
        this.userFullname = userFullname;
    }

    
    @Column(name="user_birthday", length=45)
    public String getUserBirthday() {
        return this.userBirthday;
    }
    
    public void setUserBirthday(String userBirthday) {
        this.userBirthday = userBirthday;
    }

    
    @Column(name="user_mobilephone", length=45)
    public String getUserMobilephone() {
        return this.userMobilephone;
    }
    
    public void setUserMobilephone(String userMobilephone) {
        this.userMobilephone = userMobilephone;
    }

    
    @Column(name="user_homephone", length=45)
    public String getUserHomephone() {
        return this.userHomephone;
    }
    
    public void setUserHomephone(String userHomephone) {
        this.userHomephone = userHomephone;
    }

    
    @Column(name="user_officephone", length=45)
    public String getUserOfficephone() {
        return this.userOfficephone;
    }
    
    public void setUserOfficephone(String userOfficephone) {
        this.userOfficephone = userOfficephone;
    }

    
    @Column(name="user_email", length=100)
    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    
    @Column(name="user_address", length=200)
    public String getUserAddress() {
        return this.userAddress;
    }
    
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress;
    }

    
    @Column(name="user_jobarea", length=200)
    public String getUserJobarea() {
        return this.userJobarea;
    }
    
    public void setUserJobarea(String userJobarea) {
        this.userJobarea = userJobarea;
    }

    
    @Column(name="user_job", length=45)
    public String getUserJob() {
        return this.userJob;
    }
    
    public void setUserJob(String userJob) {
        this.userJob = userJob;
    }

    
    @Column(name="user_position", length=45)
    public String getUserPosition() {
        return this.userPosition;
    }
    
    public void setUserPosition(String userPosition) {
        this.userPosition = userPosition;
    }

    
    @Column(name="user_applyyear")
    public Short getUserApplyyear() {
        return this.userApplyyear;
    }
    
    public void setUserApplyyear(Short userApplyyear) {
        this.userApplyyear = userApplyyear;
    }

    
    @Column(name="user_permission")
    public Short getUserPermission() {
        return this.userPermission;
    }
    
    public void setUserPermission(Short userPermission) {
        this.userPermission = userPermission;
    }

    
    @Column(name="user_notes", length=65535)
    public String getUserNotes() {
        return this.userNotes;
    }
    
    public void setUserNotes(String userNotes) {
        this.userNotes = userNotes;
    }

    
    @Column(name="user_roles", length=45)
    public String getUserRoles() {
        return this.userRoles;
    }
    
    public void setUserRoles(String userRoles) {
        this.userRoles = userRoles;
    }

    
    @Column(name="user_logined")
    public Integer getUserLogined() {
        return this.userLogined;
    }
    
    public void setUserLogined(Integer userLogined) {
        this.userLogined = userLogined;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="user_created_date", length=19)
    public Date getUserCreatedDate() {
        return this.userCreatedDate;
    }
    
    public void setUserCreatedDate(Date userCreatedDate) {
        this.userCreatedDate = userCreatedDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="user_edited_date", length=19)
    public Date getUserEditedDate() {
        return this.userEditedDate;
    }
    
    public void setUserEditedDate(Date userEditedDate) {
        this.userEditedDate = userEditedDate;
    }

    
    @Column(name="user_status", length=45)
    public String getUserStatus() {
        return this.userStatus;
    }
    
    public void setUserStatus(String userStatus) {
        this.userStatus = userStatus;
    }




}


