package Entities;
// Generated 31-Mar-2017 00:18:20 by Hibernate Tools 4.3.1



/**
 * Tblvalue generated by hbm2java
 */
public class Tblvalue  implements java.io.Serializable {


     private Integer valueId;
     private String value1;
     private String value2;
     private String value3;
     private String value4;
     private String value5;
     private String value6;
     private String value7;
     private String value8;
     private String value9;
     private String value10;
     private String value11;
     private String value12;
     private String value13;
     private String value14;
     private String value15;
     private String value16;
     private String value17;
     private String value18;
     private String value19;
     private String value20;
     private short valueLabelId;

    public Tblvalue() {
    }

	
    public Tblvalue(short valueLabelId) {
        this.valueLabelId = valueLabelId;
    }
    public Tblvalue(String value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, String value13, String value14, String value15, String value16, String value17, String value18, String value19, String value20, short valueLabelId) {
       this.value1 = value1;
       this.value2 = value2;
       this.value3 = value3;
       this.value4 = value4;
       this.value5 = value5;
       this.value6 = value6;
       this.value7 = value7;
       this.value8 = value8;
       this.value9 = value9;
       this.value10 = value10;
       this.value11 = value11;
       this.value12 = value12;
       this.value13 = value13;
       this.value14 = value14;
       this.value15 = value15;
       this.value16 = value16;
       this.value17 = value17;
       this.value18 = value18;
       this.value19 = value19;
       this.value20 = value20;
       this.valueLabelId = valueLabelId;
    }
   
    public Integer getValueId() {
        return this.valueId;
    }
    
    public void setValueId(Integer valueId) {
        this.valueId = valueId;
    }
    public String getValue1() {
        return this.value1;
    }
    
    public void setValue1(String value1) {
        this.value1 = value1;
    }
    public String getValue2() {
        return this.value2;
    }
    
    public void setValue2(String value2) {
        this.value2 = value2;
    }
    public String getValue3() {
        return this.value3;
    }
    
    public void setValue3(String value3) {
        this.value3 = value3;
    }
    public String getValue4() {
        return this.value4;
    }
    
    public void setValue4(String value4) {
        this.value4 = value4;
    }
    public String getValue5() {
        return this.value5;
    }
    
    public void setValue5(String value5) {
        this.value5 = value5;
    }
    public String getValue6() {
        return this.value6;
    }
    
    public void setValue6(String value6) {
        this.value6 = value6;
    }
    public String getValue7() {
        return this.value7;
    }
    
    public void setValue7(String value7) {
        this.value7 = value7;
    }
    public String getValue8() {
        return this.value8;
    }
    
    public void setValue8(String value8) {
        this.value8 = value8;
    }
    public String getValue9() {
        return this.value9;
    }
    
    public void setValue9(String value9) {
        this.value9 = value9;
    }
    public String getValue10() {
        return this.value10;
    }
    
    public void setValue10(String value10) {
        this.value10 = value10;
    }
    public String getValue11() {
        return this.value11;
    }
    
    public void setValue11(String value11) {
        this.value11 = value11;
    }
    public String getValue12() {
        return this.value12;
    }
    
    public void setValue12(String value12) {
        this.value12 = value12;
    }
    public String getValue13() {
        return this.value13;
    }
    
    public void setValue13(String value13) {
        this.value13 = value13;
    }
    public String getValue14() {
        return this.value14;
    }
    
    public void setValue14(String value14) {
        this.value14 = value14;
    }
    public String getValue15() {
        return this.value15;
    }
    
    public void setValue15(String value15) {
        this.value15 = value15;
    }
    public String getValue16() {
        return this.value16;
    }
    
    public void setValue16(String value16) {
        this.value16 = value16;
    }
    public String getValue17() {
        return this.value17;
    }
    
    public void setValue17(String value17) {
        this.value17 = value17;
    }
    public String getValue18() {
        return this.value18;
    }
    
    public void setValue18(String value18) {
        this.value18 = value18;
    }
    public String getValue19() {
        return this.value19;
    }
    
    public void setValue19(String value19) {
        this.value19 = value19;
    }
    public String getValue20() {
        return this.value20;
    }
    
    public void setValue20(String value20) {
        this.value20 = value20;
    }
    public short getValueLabelId() {
        return this.valueLabelId;
    }
    
    public void setValueLabelId(short valueLabelId) {
        this.valueLabelId = valueLabelId;
    }




}


