/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.73
 * Generated at: 2016-12-20 08:25:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\r\n");
      out.write("\"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("        <title>Photoshare - Administrator Login</title>\r\n");
      out.write("        <link href=\"../css/Administrator.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        <div id=\"\">\r\n");
      out.write("            <div class=\"\">\r\n");
      out.write("                <div class=\"padding\">\r\n");
      out.write("                    <div id=\"content\">\r\n");
      out.write("                        <div class=\"padding\">\r\n");
      out.write("                            <div id=\"element-box\" class=\"login\">\r\n");
      out.write("                                <div class=\"t\">\r\n");
      out.write("                                    <div class=\"t\">\r\n");
      out.write("                                        <div class=\"t\"></div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"m\" style=\"text-align:center\">\r\n");
      out.write("                                    <center>\r\n");
      out.write("                                        <h1> Administration Login</h1>\r\n");
      out.write("                                        \r\n");
      out.write("                                        <div id=\"section-box\">\r\n");
      out.write("                                            <div class=\"t\">\r\n");
      out.write("                                                <div class=\"t\">\r\n");
      out.write("                                                    <div class=\"t\"></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"m\">\r\n");
      out.write("                                                <form action=\"../checkLoginServlet\" method=\"post\" name=\"login\">\r\n");
      out.write("                                                    <p id=\"form-login-username\">               \r\n");
      out.write("                                                        <label for=\"UserName\">Username</label>\r\n");
      out.write("                                                        <input class=\"inputbox\" id=\"UserName\" name=\"accUser\" size=\"15\" type=\"text\" />\r\n");
      out.write("                                                    </p>\r\n");
      out.write("                                                    <p id=\"form-login-password\">\r\n");
      out.write("                                                        <label for=\"Password\">Password</label>\r\n");
      out.write("                                                        <input class=\"inputbox\" id=\"Password\" name=\"accPass\" size=\"15\" type=\"password\" />\r\n");
      out.write("                                                    </p>\r\n");
      out.write("                                                    <p id=\"form-login-rememberpass\">\r\n");
      out.write("                                                        <label for=\"modlgn_passwd\"></label>\r\n");
      out.write("                                                        Remember password <input checked id=\"isRemember\" name=\"isRemember\" type=\"checkbox\" value=\"true\" />\r\n");
      out.write("                                                    </p>\r\n");
      out.write("                                                    <p style=\"color:red\">\r\n");
      out.write("                                                        ");

                                                            if (request.getParameter("msg") != null) {
                                                                String msg = request.getParameter("msg");
                                                                if (msg.equals("failed")) {
                                                                    out.print("Username or password a not match !");
                                                                } else if (msg.equals("block")) {
                                                                    out.print("My account is blocked or not activated !");
                                                                } else {
                                                                    out.print("You have not been authorized");
                                                                }
                                                            }
                                                        
      out.write("\r\n");
      out.write("                                                    </p>\r\n");
      out.write("                                                    <div class=\"button_holder\">\r\n");
      out.write("                                                        <div class=\"button1\">\r\n");
      out.write("                                                            <div class=\"next\">\r\n");
      out.write("                                                                <a onclick=\"login.submit();\"> Login</a>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div>                                                  \r\n");
      out.write("                                                    </div>                                                 \r\n");
      out.write("                                                </form>\r\n");
      out.write("                                                <div class=\"clr\"></div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"b\">\r\n");
      out.write("                                                <div class=\"b\">\r\n");
      out.write("                                                    <div class=\"b\"></div>\r\n");
      out.write("                                                </div>\t\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </center>\r\n");
      out.write("                                    <div class=\"clr\"></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"b\">\r\n");
      out.write("                                    <div class=\"b\">\r\n");
      out.write("                                        <div class=\"b\"></div>\r\n");
      out.write("                                    </div>\t\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"clr\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"\">\r\n");
      out.write("            <div>\r\n");
      out.write("                <div></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"footer\">\r\n");
      out.write("        </div>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
