/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.39
 * Generated at: 2017-04-16 04:38:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.Guest;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<div class=\"footer\">\n");
      out.write("    <div id=\"bg-bottom\">\n");
      out.write("        <img src=\"../../Image/bg-bottom.png\" alt=\"\"/>\n");
      out.write("    </div>\n");
      out.write("    <div id=\"text-footer\">\n");
      out.write("        <p style=\"color:red;\">Khoa CNTT - Trường ĐH Công Nghiệp Hà Nội</p>\n");
      out.write("        <img src=\"../../Image/home.png\"></img>&nbsp;Địa chỉ: Tầng 6 - Nhà A1 - Khu A - P.Minh Khai, Bắc Từ Liêm, TP Hà Nội<br></br>\n");
      out.write("        <img src=\"../../Image/phone-black.png\"></img>&nbsp;Điện thoại: 84.4.7655391<br></br>\n");
      out.write("        <img src=\"../../Image/fax.png\"></img>&nbsp;Fax: 84.4.7655261<br></br>\n");
      out.write("        <img src=\"../../Image/mail-black.png\"></img>&nbsp;khoacntthaui@gmail.com\n");
      out.write("    </div>\n");
      out.write("    <div id=\"menu\">\n");
      out.write("        <p>Menu</p>\n");
      out.write("        <ul>\n");
      out.write("            <li>Trang chủ</li>\n");
      out.write("            <li>Album</li>\n");
      out.write("            <li>Tin tức</li>\n");
      out.write("            <li>Cẩm nang</li>\n");
      out.write("            <li>Giới thiệu</li>\n");
      out.write("            <li>Liên hệ</li>\n");
      out.write("        </ul>\n");
      out.write("    </div>\n");
      out.write("    <div id=\"map\">\n");
      out.write("        <p>Bản đồ</p>\n");
      out.write("        <iframe style=\"float: right;\" src=\"https://www.google.com/maps/d/embed?mid=z9hVTCL83tpc.kyLvhfCaYFLg\" height=\"245\" width=\"430\"></iframe>\t\t</div>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("<link href=\"../../css/index.css\" rel=\"stylesheet\" type=\"text/css\"/>\n");
      out.write("<link href=\"../../css/Libcss/slider1.css\" rel=\"stylesheet\" type=\"text/css\"/>\n");
      out.write("<link href=\"../../css/Libcss/responsiveslides.css\" rel=\"stylesheet\" type=\"text/css\"/>\n");
      out.write("<link href=\"../../css/Libcss/baguetteBox.css\" rel=\"stylesheet\" type=\"text/css\"/>\n");
      out.write("<script src=\"../../js/Libjs/custom.js\" type=\"text/javascript\"></script>\n");
      out.write("<script src=\"../../js/Libjs/responsiveslides.min.js\" type=\"text/javascript\"></script>\n");
      out.write("<script src=\"../../js/Libjs/baguetteBox.js\" type=\"text/javascript\"></script>\n");
      out.write("<script src=\"../../js/Libjs/plugins.js\" type=\"text/javascript\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
